export const dashboardContent = {
  en: {
    nav: {
      buffs: "Today's Buffs",
      chaos: "Chaos Chest",
      biomes: "Biomes",
      records: "Leaderboard Records",
      player: "Player Lookup",
    },
    header: {
      title: "Trove Live Dashboard",
      subtitle: "rotations & leaderboards",
      searchPlaceholder: "Look up a player by name…",
      searchButton: "Search",
      refresh: "Refresh",
      loading: "Loading Trove Dashboard...",
    },
    clock: {
      serverTime: "Server Time (UTC)",
      day: "Trove Day",
      dailyReset: "Daily reset in",
      weeklyReset: "Weekly reset in",
      weekdays: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun'],
    },
    sidebar: {
      activePlayers: "Active Players",
      onlineSub: "players online right now",
      live: "LIVE",
      chaosWeekly: "Chaos Weekly",
      corruxion: "Corruxion",
      fluxion: "Fluxion",
      active: "Active",
      away: "Away",
      voting: "Voting",
      untilReset: "until reset",
      leavesIn: "leaves in",
      arrivesIn: "arrives in",
      windowCloses: "window closes in",
      nextWindow: "next window in",
      mysteryItem: "Mystery item",
      noChaos: "No Chaos Chest data.",
      noCorruxion: "No Corruxion data.",
      noFluxion: "No Fluxion data.",
      footer: "Data via the Kiwi API (aallyn.net).",
      autoRefresh: "Auto-refreshes every 30s.",
    },
    badges: {
      unavailable: "Unavailable",
      loading: "Loading",
      live: "Live",
      activeInHub: "ACTIVE IN HUB",
      away: "AWAY",
      updates: "Updates",
    },
    buffs: {
      title: "Today's Buffs",
      unknown: "Unknown buff",
      unavailable: "Buff rotation is unavailable right now.",
    },
    weeklyBonus: {
      title: "Weekly Bonus Rotation",
      activeNow: "Active now",
      inTime: "in",
      unavailable: "Weekly buffs are unavailable right now.",
      noData: "No weekly bonus rotation data.",
      defaultDesc: "Special weekly bonus active during this week.",
    },
    biomes: {
      title: "Biome Rotation",
      current: "Current Biomes",
      next: "Next",
      unknown: "Unknown biome",
      noData: "No biome data.",
      unavailable: "Biome rotation is unavailable right now.",
    },
    records: {
      title: "Leaderboard Records",
      troveMastery: "Trove Mastery",
      geodeMastery: "Geode Mastery",
      powerRank: "Power Rank",
      unknown: "Unknown",
      unavailable: "Leaderboard records are unavailable right now.",
    },
    luxion: {
      title: "Trials of Luxion",
      overviewTitle: "The Trials of Luxion: Overview",
      overviewDesc: "The powerful dragon Luxion has left the Hub to reclaim his realm, inviting only the bravest Trovians to test their strength in a recurring, month-long event: <strong>The Trials of Luxion</strong>. Active for one week each month, this deadly new gameplay mode challenges players to collect <strong>Venturine</strong>—a temporary currency used to craft exclusive rewards from Luxion’s hoard—while facing strict limitations, suppressed combat stats, and a penalty of lost Venturine upon death.",
      gettingStartedTitle: "Getting Started & Entering the Realm",
      gettingStartedDesc: "To join, eligible Trovians must use the portal in <strong>Light’s Den</strong> within the Hub. Access requires crafting a <strong>Luxion’s Pact</strong> at the Luxion’s Pact Register using an <em>Unfortunate Soul</em>, which can be crafted (with daily escalating Flux costs) or bought via Credits and Cubits from <em>Soul-Reckoner Suri</em>. New players can follow the dedicated questline in their Adventures UI to get started.",
      progressionTitle: "Trial Progression & Scaling Difficulty",
      progressionDesc: "Inside <strong>The Venture Capitol</strong>, players encounter Lord Primalux, who offers three sequential quest lines to defeat enemies in the Inner, Middle, and Outer rings. Upon completion, players can choose their path:",
      completeTrials: "Complete the Trials:",
      completeTrialsDesc: "Satisfies the Pact for a massive Venturine payout and exits the instance after 10 seconds.",
      progressTrials: "Progress the Trials:",
      progressTrialsDesc: "Gives no instant reward, but upgrades the Pact to the next difficulty rank (ranging from Moonless Dark 10 to Long Shade 15), increasing future rewards.",
      rewardsTitle: "Rewards, Mechanics & Risks",
      rewardsDesc: "Players can use the <strong>Venturine Forge</strong> to convert currency into <strong>Venturine Signets</strong> to unlock Luxion’s cycling hoard of collectibles. Players can also obtain temporary <em>Luxion’s Favor</em> buffs by Loot Collecting Unfortunate Souls, or test their luck at <em>Luxion’s Long Shots</em> by donating items for extra Venturine and rare Stashes.",
      notesTitle: "⚠️ Important Notes",
      rule1Title: "Rules of the Realm:",
      rule1Desc: "Jump and Movement Speed are capped, Build Mode and block destruction are disabled, and social features (joining or inviting) are unavailable.",
      rule2Title: "Use It or Lose It:",
      rule2Desc: "Death deducts Venturine from your inventory. Furthermore, all Venturine, Signets, and Stashes <strong>disappear when the event ends</strong>, so be sure to spend and open everything before time runs out!",
      leavesHubIn: "Leaves the Hub in",
      nextArrival: "Next arrival",
      scheduleTba: "Schedule TBA",
    },
    news: {
      title: "Trove News",
      loading: "Loading latest news...",
      error: "Could not load news articles.",
      defaultTitle: "Trove Update",
      recent: "Recent",
    },
    bannerError: "— showing the last data we had, if any.",
  },

  fr: {
    nav: {
      buffs: "Bonus du jour",
      chaos: "Coffre du Chaos",
      biomes: "Biomes",
      records: "Records Classement",
      player: "Recherche Joueur",
    },
    header: {
      title: "Tableau de bord Trove Live",
      subtitle: "rotations et classements",
      searchPlaceholder: "Rechercher un joueur par pseudo…",
      searchButton: "Chercher",
      refresh: "Actualiser",
      loading: "Chargement du tableau de bord Trove...",
    },
    clock: {
      serverTime: "Heure Serveur (UTC)",
      day: "Jour Trove",
      dailyReset: "Réinitialisation quotidienne dans",
      weeklyReset: "Réinitialisation hebdomadaire dans",
      weekdays: ['Lun', 'Mar', 'Mer', 'Jeu', 'Ven', 'Sam', 'Dim'],
    },
    sidebar: {
      activePlayers: "Joueurs Actifs",
      onlineSub: "joueurs en ligne actuellement",
      live: "EN DIRECT",
      chaosWeekly: "Chaos de la Semaine",
      corruxion: "Corruxion",
      fluxion: "Fluxion",
      active: "Actif",
      away: "Absent",
      voting: "Vote en cours",
      untilReset: "avant réinitialisation",
      leavesIn: "départ dans",
      arrivesIn: "arrivée dans",
      windowCloses: "fermeture dans",
      nextWindow: "prochaine fenêtre dans",
      mysteryItem: "Objet mystère",
      noChaos: "Aucune donnée de Coffre du Chaos.",
      noCorruxion: "Aucune donnée Corruxion.",
      noFluxion: "Aucune donnée Fluxion.",
      footer: "Données via l'API Kiwi (aallyn.net).",
      autoRefresh: "Actualisation auto toutes les 30s.",
    },
    badges: {
      unavailable: "Indisponible",
      loading: "Chargement",
      live: "En direct",
      activeInHub: "ACTIF DANS LE HUB",
      away: "ABSENT",
      updates: "Mises à jour",
    },
    buffs: {
      title: "Bonus du Jour",
      unknown: "Bonus inconnu",
      unavailable: "La rotation des bonus est indisponible pour le moment.",
    },
    weeklyBonus: {
      title: "Rotation des Bonus Hebdo",
      activeNow: "Actif maintenant",
      inTime: "dans",
      unavailable: "Les bonus hebdomadaires sont indisponibles.",
      noData: "Aucune donnée de rotation hebdomadaire.",
      defaultDesc: "Bonus hebdomadaire spécial actif cette semaine.",
    },
    biomes: {
      title: "Rotation des Biomes",
      current: "Biomes Actuels",
      next: "Suivant",
      unknown: "Biome inconnu",
      noData: "Aucune donnée de biome.",
      unavailable: "La rotation des biomes est indisponible.",
    },
    records: {
      title: "Records du Classement",
      troveMastery: "Maîtrise Trove",
      geodeMastery: "Maîtrise Géode",
      powerRank: "Rang de Puissance",
      unknown: "Inconnu",
      unavailable: "Les records du classement sont indisponibles.",
    },
    luxion: {
      title: "Épreuves de Luxion",
      overviewTitle: "Les Épreuves de Luxion : Vue d'ensemble",
      overviewDesc: "Le puissant dragon Luxion a quitté le Hub pour reconquérir son royaume, invitant les Troviens les plus braves à tester leur force dans un événement mensuel récurrent : <strong>Les Épreuves de Luxion</strong>. Actif une semaine par mois, ce mode de jeu mortel met les joueurs au défi de collecter de la <strong>Venturine</strong> pour fabriquer des récompenses exclusives, tout en subissant des restrictions strictes et la perte de Venturine en cas de mort.",
      gettingStartedTitle: "Commencer & Entrer dans le Royaume",
      gettingStartedDesc: "Pour participer, les Troviens éligibles doivent emprunter le portail dans le <strong>Repaire de la Lumière</strong> au Hub. L'accès nécessite la fabrication d'un <strong>Pacte de Luxion</strong> au Registre avec une <em>Âme Infortunée</em>, achetable en Flux, Crédits ou Cubits auprès de <em>Suri la Compteuse d'Âmes</em>.",
      progressionTitle: "Progression & Difficulté Évolutive",
      progressionDesc: "Dans <strong>The Venture Capitol</strong>, les joueurs rencontrent Lord Primalux qui propose 3 quêtes successives pour vaincre les ennemis. À la fin, les joueurs choisissent leur voie :",
      completeTrials: "Terminer les Épreuves :",
      completeTrialsDesc: "Valide le Pacte pour un gain massif de Venturine et quitte l'instance après 10 secondes.",
      progressTrials: "Poursuivre les Épreuves :",
      progressTrialsDesc: "N'offre aucune récompense instantanée, mais améliore le Pacte au rang supérieur pour augmenter les gains futurs.",
      rewardsTitle: "Récompenses, Mécaniques & Risques",
      rewardsDesc: "Utilisez la <strong>Forge de Venturine</strong> pour transformer la monnaie en <strong>Sceaux de Venturine</strong> et débloquer les collections de Luxion. Obtenez également des bonus temporaires via la récupération d'âmes.",
      notesTitle: "⚠️ Remarques Importantes",
      rule1Title: "Règles du Royaume :",
      rule1Desc: "Saut et Vitesse de déplacement limités, Mode Construction désactivé et fonctionnalités sociales indisponibles.",
      rule2Title: "Utilisez ou Perdez :",
      rule2Desc: "La mort déduit de la Venturine de votre inventaire. De plus, toute la Venturine et les Sceaux <strong>disparaissent à la fin de l'événement</strong> !",
      leavesHubIn: "Quitte le Hub dans",
      nextArrival: "Prochaine arrivée",
      scheduleTba: "Calendrier à venir",
    },
    news: {
      title: "Actualités Trove",
      loading: "Chargement des actualités...",
      error: "Impossible de charger les articles.",
      defaultTitle: "Mise à jour Trove",
      recent: "Récemment",
    },
    bannerError: "— affichage des dernières données reçues, si disponibles.",
  },

  es: {
    nav: {
      buffs: "Ventajas de Hoy",
      chaos: "Cofre del Caos",
      biomes: "Biomas",
      records: "Récords de Clasificación",
      player: "Buscar Jugador",
    },
    header: {
      title: "Panel Trove en Vivo",
      subtitle: "rotaciones y clasificaciones",
      searchPlaceholder: "Buscar jugador por nombre…",
      searchButton: "Buscar",
      refresh: "Actualizar",
      loading: "Cargando Panel de Trove...",
    },
    clock: {
      serverTime: "Hora del Servidor (UTC)",
      day: "Día de Trove",
      dailyReset: "Reinicio diario en",
      weeklyReset: "Reinicio semanal en",
      weekdays: ['Lun', 'Mar', 'Mié', 'Jue', 'Vie', 'Sáb', 'Dom'],
    },
    sidebar: {
      activePlayers: "Jugadores Activos",
      onlineSub: "jugadores conectados ahora",
      live: "EN VIVO",
      chaosWeekly: "Caos Semanal",
      corruxion: "Corruxion",
      fluxion: "Fluxion",
      active: "Activo",
      away: "Ausente",
      voting: "Votación",
      untilReset: "para reinicio",
      leavesIn: "se va en",
      arrivesIn: "llega en",
      windowCloses: "la ventana cierra en",
      nextWindow: "próxima ventana en",
      mysteryItem: "Objeto misterioso",
      noChaos: "Sin datos del Cofre del Caos.",
      noCorruxion: "Sin datos de Corruxion.",
      noFluxion: "Sin datos de Fluxion.",
      footer: "Datos a través de la API Kiwi (aallyn.net).",
      autoRefresh: "Actualización auto cada 30s.",
    },
    badges: {
      unavailable: "No disponible",
      loading: "Cargando",
      live: "En vivo",
      activeInHub: "ACTIVO EN EL HUB",
      away: "AUSENTE",
      updates: "Novedades",
    },
    buffs: {
      title: "Ventajas de Hoy",
      unknown: "Ventaja desconocida",
      unavailable: "La rotación de ventajas no está disponible en este momento.",
    },
    weeklyBonus: {
      title: "Rotación de Bonus Semanal",
      activeNow: "Activo ahora",
      inTime: "en",
      unavailable: "Las ventajas semanales no están disponibles.",
      noData: "Sin datos de rotación semanal.",
      defaultDesc: "Bonus semanal especial activo durante esta semana.",
    },
    biomes: {
      title: "Rotación de Biomas",
      current: "Biomas Actuales",
      next: "Siguiente",
      unknown: "Bioma desconocido",
      noData: "Sin datos de biomas.",
      unavailable: "La rotación de biomas no está disponible.",
    },
    records: {
      title: "Récords de Clasificación",
      troveMastery: "Maestría de Trove",
      geodeMastery: "Maestría de Geoda",
      powerRank: "Rango de Poder",
      unknown: "Desconocido",
      unavailable: "Los récords no están disponibles.",
    },
    luxion: {
      title: "Pruebas de Luxion",
      overviewTitle: "Las Pruebas de Luxion: Información General",
      overviewDesc: "El poderoso dragón Luxion ha dejado el Hub para reclamar su reino, invitando a los trovanos más valientes a probar su fuerza en un evento mensual recurrente: <strong>Las Pruebas de Luxion</strong>. Activo una semana cada mes, desafía a los jugadores a recolectar <strong>Venturine</strong> para fabricar recompensas exclusivas mientras enfrentan duras restricciones.",
      gettingStartedTitle: "Primeros Pasos y Acceso al Reino",
      gettingStartedDesc: "Para unirse, use el portal en la <strong>Guarida de la Luz</strong> en el Hub. Se requiere fabricar un <strong>Pacto de Luxion</strong> usando un <em>Alma Desafortunada</em>, que se puede conseguir con Flux, Créditos o Cubits.",
      progressionTitle: "Progresión y Dificultad",
      progressionDesc: "Dentro de <strong>The Venture Capitol</strong>, Lord Primalux ofrece misiones para derrotar enemigos. Al completarlas, los jugadores eligen su camino:",
      completeTrials: "Completar las Pruebas:",
      completeTrialsDesc: "Cumple el Pacto para recibir una gran recompensa de Venturine y salir tras 10 segundos.",
      progressTrials: "Progresar en las Pruebas:",
      progressTrialsDesc: "No da recompensa inmediata, pero sube de rango el Pacto para aumentar las futuras ganancias.",
      rewardsTitle: "Recompensas y Mecánicas",
      rewardsDesc: "Usa la <strong>Forja de Venturine</strong> para desbloquear coleccionables exclusivos de Luxion.",
      notesTitle: "⚠️ Notas Importantes",
      rule1Title: "Reglas del Reino:",
      rule1Desc: "Velocidad de movimiento y salto limitados, modo construcción deshabilitado y funciones sociales inaccesibles.",
      rule2Title: "Úsalo o Piérdelo:",
      rule2Desc: "Morir resta Venturine de tu inventario. ¡Además, toda la Venturine y Sellos <strong>desaparecen al finalizar el evento</strong>!",
      leavesHubIn: "Sale del Hub en",
      nextArrival: "Próxima llegada",
      scheduleTba: "Horario por confirmar",
    },
    news: {
      title: "Noticias de Trove",
      loading: "Cargando últimas noticias...",
      error: "No se pudieron cargar las noticias.",
      defaultTitle: "Actualización de Trove",
      recent: "Reciente",
    },
    bannerError: "— mostrando los últimos datos disponibles.",
  },

  zh: {
    nav: {
      buffs: "今日增益",
      chaos: "混沌宝箱",
      biomes: "生态群落",
      records: "排行榜纪录",
      player: "玩家查询",
    },
    header: {
      title: "Trove 实时数据看板",
      subtitle: "轮换与排行榜数据",
      searchPlaceholder: "输入玩家名称进行查询…",
      searchButton: "查询",
      refresh: "刷新",
      loading: "正在加载 Trove 看板数据...",
    },
    clock: {
      serverTime: "服务器时间 (UTC)",
      day: "Trove 第几天",
      dailyReset: "每日重置倒计时",
      weeklyReset: "每周重置倒计时",
      weekdays: ['周一', '周二', '周三', '周四', '周五', '周六', '周日'],
    },
    sidebar: {
      activePlayers: "在线玩家",
      onlineSub: "当前全网在线玩家",
      live: "实时",
      chaosWeekly: "本周混沌宝箱",
      corruxion: "腐化龙 (Corruxion)",
      fluxion: "投票龙 (Fluxion)",
      active: "已到来",
      away: "未到达",
      voting: "投票中",
      untilReset: "后重置",
      leavesIn: "离去倒计时",
      arrivesIn: "到来倒计时",
      windowCloses: "窗口关闭倒计时",
      nextWindow: "下一轮窗口倒计时",
      mysteryItem: "神秘物品",
      noChaos: "暂无混沌宝箱数据。",
      noCorruxion: "暂无腐化龙数据。",
      noFluxion: "暂无投票龙数据。",
      footer: "数据来自 Kiwi API (aallyn.net)。",
      autoRefresh: "每 30 秒自动刷新一次。",
    },
    badges: {
      unavailable: "不可用",
      loading: "加载中",
      live: "在线",
      activeInHub: "已在主城中",
      away: "未在主城",
      updates: "更新",
    },
    buffs: {
      title: "今日日常增益",
      unknown: "未知增益",
      unavailable: "增益轮换数据当前不可用。",
    },
    weeklyBonus: {
      title: "每周活动增益轮换",
      activeNow: "当前生效中",
      inTime: "距离生效还剩",
      unavailable: "每周增益数据不可用。",
      noData: "暂无每周增益轮换数据。",
      defaultDesc: "本周激活的特殊周常增益。",
    },
    biomes: {
      title: "群落轮换",
      current: "当前群落",
      next: "下一轮群落",
      unknown: "未知群落",
      noData: "暂无群落数据。",
      unavailable: "群落轮换数据暂不可用。",
    },
    records: {
      title: "全服排行榜纪录",
      troveMastery: "Trove 专精",
      geodeMastery: "Geode 专精",
      powerRank: "战斗力等级 (PR)",
      unknown: "未知玩家",
      unavailable: "排行榜纪录暂不可用。",
    },
    luxion: {
      title: "Luxion 的试炼 (Trials of Luxion)",
      overviewTitle: "Luxion 的试炼：模式总览",
      overviewDesc: "巨龙 Luxion 离开了主城去夺回他的领地，仅邀请最勇敢的玩家在每月为期一周的常规事件中证明自己的力量：<strong>Luxion 的试炼</strong>。玩家需要收集<strong>Venturine（砂金石）</strong>以兑换独家限定藏品，同时面临严苛的战斗属性压制及阵亡扣除代币的惩罚。",
      gettingStartedTitle: "新手入门与进入领域",
      gettingStartedDesc: "符合资格的玩家需要通过主城中的<strong>光芒之穴 (Light’s Den)</strong>传送门进入。进入需要使用<em>不幸灵魂 (Unfortunate Soul)</em>在契约登记处制作<strong>Luxion 的契约 (Luxion's Pact)</strong>。",
      progressionTitle: "试炼阶段与难度提升",
      progressionDesc: "在<strong>风投之都 (The Venture Capitol)</strong>内，玩家可以接受 Lord Primalux 的连续任务击败内环、中环与外环的敌人。完成后可自由选择路线：",
      completeTrials: "完成试炼：",
      completeTrialsDesc: "完成契约获得大量 Venturine 奖励并在 10 秒后离开副本。",
      progressTrials: "提升试炼：",
      progressTrialsDesc: "不直接发放奖励，但会将契约升级至更高难度阶位，以增加未来的奖励收益。",
      rewardsTitle: "奖励、机制与风险",
      rewardsDesc: "玩家可以使用<strong>砂金石锻造台 (Venturine Forge)</strong>将代币转换为印章，解锁 Luxion 轮换的收藏宝库。",
      notesTitle: "⚠️ 重要注意事项",
      rule1Title: "领域规则：",
      rule1Desc: "跳跃和移动速度受到上限限制，建造模式和方块破坏被禁用，社交功能（加入/邀请）不可用。",
      rule2Title: "及时兑换，过期清空：",
      rule2Desc: "在领域内死亡会扣除背包中的 Venturine。此外，所有 Venturine、印章和宝箱在<strong>活动结束时将全部消失清空</strong>，请务必在倒计时结束前使用完毕！",
      leavesHubIn: "离开主城倒计时",
      nextArrival: "距离下次到来",
      scheduleTba: "具体排期待定",
    },
    news: {
      title: "Trove 官方新闻",
      loading: "正在加载最新新闻资讯...",
      error: "无法加载新闻文章。",
      defaultTitle: "Trove 资讯更新",
      recent: "近期发布",
    },
    bannerError: "— 当前显示已缓存的最后数据。",
  }
};