export const dashboardContent = {
  en: {
    nav: {
      buffs: "Today's Buffs",
      chaos: "Chaos Chest",
      biomes: "Biomes",
      records: "Leaderboard Records",
      player: "Player Lookup",
    },
    header: {
      title: "Trove Live Dashboard",
      subtitle: "rotations & leaderboards",
      searchPlaceholder: "Look up a player by name…",
      searchButton: "Search",
      refresh: "Refresh",
      loading: "Loading Trove Dashboard...",
    },
    clock: {
      serverTime: "Server Time (UTC)",
      day: "Trove Day",
      dailyReset: "Daily reset in",
      weeklyReset: "Weekly reset in",
      weekdays: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun'],
    },
    sidebar: {
      activePlayers: "Active Players",
      onlineSub: "players online right now",
      live: "LIVE",
      chaosWeekly: "Chaos Weekly",
      corruxion: "Corruxion",
      fluxion: "Fluxion",
      active: "Active",
      away: "Away",
      voting: "Voting",
      untilReset: "until reset",
      leavesIn: "leaves in",
      arrivesIn: "arrives in",
      windowCloses: "window closes in",
      nextWindow: "next window in",
      mysteryItem: "Mystery item",
      noChaos: "No Chaos Chest data.",
      noCorruxion: "No Corruxion data.",
      noFluxion: "No Fluxion data.",
      footer: "Data via the Kiwi API (aallyn.net).",
      autoRefresh: "Auto-refreshes every 30s.",
    },
    badges: {
      unavailable: "Unavailable",
      loading: "Loading",
      live: "Live",
      activeInHub: "ACTIVE IN HUB",
      away: "AWAY",
      updates: "Updates",
    },
    buffs: {
      title: "Today's Buffs",
      unknown: "Unknown buff",
      unavailable: "Buff rotation is unavailable right now.",
    },
    buffNames: {
      "Gathering Day": "Gathering Day",
      "XP Day": "XP Day",
      "Mining Day": "Mining Day",
      "Gem Day": "Gem Day",
      "Dragon Day": "Dragon Day",
      "Loot Day": "Loot Day",
      "Arena Day": "Arena Day",
      "Shadow Day": "Shadow Day",
      "Chaos Day": "Chaos Day",
    },
    buffDescriptions: {
      "double Radiant Shard Drops": "Double Radiant Shard Drops",
      "20% Bonus Harvest Chance": "20% Bonus Harvest Chance",
      "50% Bonus Ore Chance": "50% Bonus Ore Chance",
      "20% Bonus Fish Chance": "20% Bonus Fish Chance",
      "Triple Radiant Shard Drops": "Triple Radiant Shard Drops",
      "40% Bonus Harvest Chance": "40% Bonus Harvest Chance",
      "100% Bonus Ore Chance": "100% Bonus Ore Chance",
      "40% Bonus Fish Chance": "40% Bonus Fish Chance",
      "Double Dragon Coin Drops": "Double Dragon Coin Drops",
      "Double Star Bar Payouts": "Double Star Bar Payouts",
      "50% Bonus Adventure XP": "50% Bonus Adventure XP",
      "100% Bonus Adventure XP": "100% Bonus Adventure XP",
      "Double Gem Dust Drops": "Double Gem Dust Drops",
      "Triple Gem Dust Drops": "Triple Gem Dust Drops",
      "Double Chaos Chest Drops": "Double Chaos Chest Drops",
      "Triple Chaos Chest Drops": "Triple Chaos Chest Drops",
      "Double Shadow Key Fragment Drops": "Double Shadow Key Fragment Drops",
      "Triple Shadow Key Fragment Drops": "Triple Shadow Key Fragment Drops",
    },
    weeklyBonus: {
      title: "Weekly Bonus Rotation",
      activeNow: "Active now",
      inTime: "in",
      unavailable: "Weekly buffs are unavailable right now.",
      noData: "No weekly bonus rotation data.",
      defaultDesc: "Special weekly bonus active during this week.",
    },
    biomes: {
      title: "Biome Rotation",
      current: "Current Biomes",
      next: "Next",
      unknown: "Unknown biome",
      noData: "No biome data.",
      unavailable: "Biome rotation is unavailable right now.",
    },
    records: {
      title: "Leaderboard Records",
      troveMastery: "Trove Mastery",
      geodeMastery: "Geode Mastery",
      powerRank: "Power Rank",
      unknown: "Unknown",
      unavailable: "Leaderboard records are unavailable right now.",
    },
    luxion: {
      title: "Trials of Luxion",
      overviewTitle: "The Trials of Luxion: Overview",
      overviewDesc: "The powerful dragon Luxion has left the Hub to reclaim his realm, inviting only the bravest Trovians to test their strength in a recurring, month-long event: <strong>The Trials of Luxion</strong>. Active for one week each month, this deadly new gameplay mode challenges players to collect <strong>Venturine</strong>—a temporary currency used to craft exclusive rewards from Luxion’s hoard—while facing strict limitations, suppressed combat stats, and a penalty of lost Venturine upon death.",
      gettingStartedTitle: "Getting Started & Entering the Realm",
      gettingStartedDesc: "To join, eligible Trovians must use the portal in <strong>Light’s Den</strong> within the Hub. Access requires crafting a <strong>Luxion’s Pact</strong> at the Luxion’s Pact Register using an <em>Unfortunate Soul</em>, which can be crafted (with daily escalating Flux costs) or bought via Credits and Cubits from <em>Soul-Reckoner Suri</em>. New players can follow the dedicated questline in their Adventures UI to get started.",
      progressionTitle: "Trial Progression & Scaling Difficulty",
      progressionDesc: "Inside <strong>The Venture Capitol</strong>, players encounter Lord Primalux, who offers three sequential quest lines to defeat enemies in the Inner, Middle, and Outer rings. Upon completion, players can choose their path:",
      completeTrials: "Complete the Trials:",
      completeTrialsDesc: "Satisfies the Pact for a massive Venturine payout and exits the instance after 10 seconds.",
      progressTrials: "Progress the Trials:",
      progressTrialsDesc: "Gives no instant reward, but upgrades the Pact to the next difficulty rank (ranging from Moonless Dark 10 to Long Shade 15), increasing future rewards.",
      rewardsTitle: "Rewards, Mechanics & Risks",
      rewardsDesc: "Players can use the <strong>Venturine Forge</strong> to convert currency into <strong>Venturine Signets</strong> to unlock Luxion’s cycling hoard of collectibles. Players can also obtain temporary <em>Luxion’s Favor</em> buffs by Loot Collecting Unfortunate Souls, or test their luck at <em>Luxion’s Long Shots</em> by donating items for extra Venturine and rare Stashes.",
      notesTitle: "⚠️ Important Notes",
      rule1Title: "Rules of the Realm:",
      rule1Desc: "Jump and Movement Speed are capped, Build Mode and block destruction are disabled, and social features (joining or inviting) are unavailable.",
      rule2Title: "Use It or Lose It:",
      rule2Desc: "Death deducts Venturine from your inventory. Furthermore, all Venturine, Signets, and Stashes <strong>disappear when the event ends</strong>, so be sure to spend and open everything before time runs out!",
      leavesHubIn: "Leaves the Hub in",
      nextArrival: "Next arrival",
      scheduleTba: "Schedule TBA",
      eventCalendarBtn: "Event Calendar",
      fastTrialsEndsIn: "Fast trials ends in",
      nextFastTrialsIn: "Next fast trials in"
    },
    trials: {
      whatIsTitle: "What is Fast Trials?",
      whatIsP1: "Fast Trials is a special event rotation during which the spawn rate of Invaders is increased. This 3-hour window allows players to collect as many Venturines as possible.",
      whatIsP2: "When this rotation is active, players must open a D13 Portal to a Trials World. Every player participating must be on either the EU or NA server; otherwise, they will not be able to join the same world as the others. Players then AFK in a designated flat area, which they must find themselves, allowing them to collect thousands of Venturines during the 3-hour rotation.",
      methodTitle: "What is the method?",
      methodP1: "One player announces the 3-hour rotation so that other players can join the same hub as the announcer. After that, every participating player must open a D13 Portal and decide which server they will host on — either EU or NA.",
      methodP2: "Most players usually set a timer so that everyone can join the portals at roughly the same time. Once the players have joined, one of them needs to find a suitable flat area where the AFK session will take place.",
      methodP3: "When a player finds a suitable area, they need to place an Origin Portal, which allows the rest of the players to travel to the location where the AFK session will take place. The AFK session usually lasts for the full 3 hours, but each player can decide for themselves whether they want to stay until the end or leave the host earlier."
    },
    news: {
      title: "Trove News",
      loading: "Loading latest news...",
      error: "Could not load news articles.",
      defaultTitle: "Trove Update",
      recent: "Recent",
    },
    bannerError: "— showing the last data we had, if any.",
  },

  fr: {
    nav: {
      buffs: "Bonus du jour",
      chaos: "Coffre du Chaos",
      biomes: "Biomes",
      records: "Records Classement",
      player: "Recherche Joueur",
    },
    header: {
      title: "Tableau de bord Trove Live",
      subtitle: "rotations et classements",
      searchPlaceholder: "Rechercher un joueur par pseudo…",
      searchButton: "Chercher",
      refresh: "Actualiser",
      loading: "Chargement du tableau de bord Trove...",
    },
    clock: {
      serverTime: "Heure Serveur (UTC)",
      day: "Jour Trove",
      dailyReset: "Réinitialisation quotidienne dans",
      weeklyReset: "Réinitialisation hebdomadaire dans",
      weekdays: ['Lun', 'Mar', 'Mer', 'Jeu', 'Ven', 'Sam', 'Dim'],
    },
    sidebar: {
      activePlayers: "Joueurs Actifs",
      onlineSub: "joueurs en ligne actuellement",
      live: "EN DIRECT",
      chaosWeekly: "Chaos de la Semaine",
      corruxion: "Corruxion",
      fluxion: "Fluxion",
      active: "Actif",
      away: "Absent",
      voting: "Vote en cours",
      untilReset: "avant réinitialisation",
      leavesIn: "départ dans",
      arrivesIn: "arrivée dans",
      windowCloses: "fermeture dans",
      nextWindow: "prochaine fenêtre dans",
      mysteryItem: "Objet mystère",
      noChaos: "Aucune donnée de Coffre du Chaos.",
      noCorruxion: "Aucune donnée Corruxion.",
      noFluxion: "Aucune donnée Fluxion.",
      footer: "Données via l'API Kiwi (aallyn.net).",
      autoRefresh: "Actualisation auto toutes les 30s.",
    },
    badges: {
      unavailable: "Indisponible",
      loading: "Chargement",
      live: "En direct",
      activeInHub: "ACTIF DANS LE HUB",
      away: "ABSENT",
      updates: "Mises à jour",
    },
    buffs: {
      title: "Bonus du Jour",
      unknown: "Bonus inconnu",
      unavailable: "La rotation des bonus est indisponible pour le moment.",
    },
    buffNames: {
      "Gathering Day": "Jour de Récolte",
      "XP Day": "Jour d'XP",
      "Mining Day": "Jour de Minage",
      "Gem Day": "Jour des Gemmes",
      "Dragon Day": "Jour des Dragons",
      "Loot Day": "Jour de Butin",
      "Arena Day": "Jour d'Arène",
      "Shadow Day": "Jour des Ombres",
      "Chaos Day": "Jour du Chaos",
    },
    buffDescriptions: {
      "double Radiant Shard Drops": "Fragments Radiants x2",
      "20% Bonus Harvest Chance": "+20% Chance de Récolte",
      "50% Bonus Ore Chance": "+50% Chance de Minerais",
      "20% Bonus Fish Chance": "+20% Chance de Pêche",
      "Triple Radiant Shard Drops": "Fragments Radiants x3",
      "40% Bonus Harvest Chance": "+40% Chance de Récolte",
      "100% Bonus Ore Chance": "+100% Chance de Minerais",
      "40% Bonus Fish Chance": "+40% Chance de Pêche",
      "Double Dragon Coin Drops": "Pièces de Dragon x2",
      "Double Star Bar Payouts": "Barre d'Étoile x2",
      "50% Bonus Adventure XP": "+50% XP d'Aventure",
      "100% Bonus Adventure XP": "+100% XP d'Aventure",
      "Double Gem Dust Drops": "Poussières de Gemmes x2",
      "Triple Gem Dust Drops": "Poussières de Gemmes x3",
      "Double Chaos Chest Drops": "Coffres du Chaos x2",
      "Triple Chaos Chest Drops": "Coffres du Chaos x3",
      "Double Shadow Key Fragment Drops": "Fragments de Clé d'Ombre x2",
      "Triple Shadow Key Fragment Drops": "Fragments de Clé d'Ombre x3",
    },
    weeklyBonus: {
      title: "Rotation des Bonus Hebdo",
      activeNow: "Actif maintenant",
      inTime: "dans",
      unavailable: "Les bonus hebdomadaires sont indisponibles.",
      noData: "Aucune donnée de rotation hebdomadaire.",
      defaultDesc: "Bonus hebdomadaire spécial actif cette semaine.",
    },
    biomes: {
      title: "Rotation des Biomes",
      current: "Biomes Actuels",
      next: "Suivant",
      unknown: "Biome inconnu",
      noData: "Aucune donnée de biome.",
      unavailable: "La rotation des biomes est indisponible.",
    },
    records: {
      title: "Records du Classement",
      troveMastery: "Maîtrise Trove",
      geodeMastery: "Maîtrise Géode",
      powerRank: "Rang de Puissance",
      unknown: "Inconnu",
      unavailable: "Les records du classement sont indisponibles.",
    },
    luxion: {
      title: "Épreuves de Luxion",
      overviewTitle: "Les Épreuves de Luxion : Vue d'ensemble",
      overviewDesc: "Le puissant dragon Luxion a quitté le Hub pour reconquérir son royaume, invitant les Troviens les plus braves à tester leur force dans un événement mensuel récurrent : <strong>Les Épreuves de Luxion</strong>. Actif une semaine par mois, ce mode de jeu mortel met les joueurs au défi de collecter de la <strong>Venturine</strong> pour fabriquer des récompenses exclusives, tout en subissant des restrictions strictes et la perte de Venturine en cas de mort.",
      gettingStartedTitle: "Commencer & Entrer dans le Royaume",
      gettingStartedDesc: "Pour participer, les Troviens éligibles doivent emprunter le portail dans le <strong>Repaire de la Lumière</strong> au Hub. L'accès nécessite la fabrication d'un <strong>Pacte de Luxion</strong> au Registre avec une <em>Âme Infortunée</em>, achetable en Flux, Crédits ou Cubits auprès de <em>Suri la Compteuse d'Âmes</em>.",
      progressionTitle: "Progression & Difficulté Évolutive",
      progressionDesc: "Dans <strong>The Venture Capitol</strong>, les joueurs rencontrent Lord Primalux qui propose 3 quêtes successives pour vaincre les ennemis. À la fin, les joueurs choisissent leur voie :",
      completeTrials: "Terminer les Épreuves :",
      completeTrialsDesc: "Valide le Pacte pour un gain massif de Venturine et quitte l'instance après 10 secondes.",
      progressTrials: "Poursuivre les Épreuves :",
      progressTrialsDesc: "N'offre aucune récompense instantanée, mais améliore le Pacte au rang supérieur pour augmenter les gains futurs.",
      rewardsTitle: "Récompenses, Mécaniques & Risques",
      rewardsDesc: "Utilisez la <strong>Forge de Venturine</strong> pour transformer la monnaie en <strong>Sceaux de Venturine</strong> et débloquer les collections de Luxion. Obtenez également des bonus temporaires via la récupération d'âmes.",
      notesTitle: "⚠️ Remarques Importantes",
      rule1Title: "Règles du Royaume :",
      rule1Desc: "Saut et Vitesse de déplacement limités, Mode Construction désactivé et fonctionnalités sociales indisponibles.",
      rule2Title: "Utilisez ou Perdez :",
      rule2Desc: "La mort déduit de la Venturine de votre inventaire. De plus, toute la Venturine et les Sceaux <strong>disparaissent à la fin de l'événement</strong> !",
      leavesHubIn: "Quitte le Hub dans",
      nextArrival: "Prochaine arrivée",
      scheduleTba: "Calendrier à venir",
      eventCalendarBtn: "Calendrier de l'Événement",
      fastTrialsEndsIn: "Les épreuves rapides se terminent dans",
      nextFastTrialsIn: "Prochaines épreuves rapides dans"
    },
    trials: {
      whatIsTitle: "Que sont les Épreuves Rapides ?",
      whatIsP1: "Les Épreuves Rapides sont une rotation spéciale au cours de laquelle le taux d'apparition des envahisseurs est augmenté. Cette fenêtre de 3 heures permet de récolter autant de Venturines que possible.",
      whatIsP2: "Lorsque cette rotation est active, les joueurs doivent ouvrir un Portail D13 vers un Monde d'Épreuves. Chaque joueur doit être sur le serveur EU ou NA, sinon il ne pourra pas rejoindre le même monde. Les joueurs restent ensuite AFK dans une zone plate pour collecter des milliers de Venturines.",
      methodTitle: "Quelle est la méthode ?",
      methodP1: "Un joueur annonce la rotation de 3 heures afin que les autres puissent rejoindre le même hub. Ensuite, chaque participant ouvre un Portail D13 et choisit le serveur hôte (EU ou NA).",
      methodP2: "La plupart des joueurs utilisent un minuteur pour entrer dans les portails en même temps. Une fois réunis, un joueur part en repérage pour trouver une zone plate adaptée à la session AFK.",
      methodP3: "Dès que la zone est trouvée, il place un Portail d'Origine permettant aux autres de se téléporter. La session AFK dure généralement 3 heures complètes, mais chacun est libre de partir plus tôt."
    },
    news: {
      title: "Actualités Trove",
      loading: "Chargement des actualités...",
      error: "Impossible de charger les articles.",
      defaultTitle: "Mise à jour Trove",
      recent: "Récemment",
    },
    bannerError: "— affichage des dernières données reçues, si disponibles.",
  },

  es: {
    nav: {
      buffs: "Ventajas de Hoy",
      chaos: "Cofre del Caos",
      biomes: "Biomas",
      records: "Récords de Clasificación",
      player: "Buscar Jugador",
    },
    header: {
      title: "Panel Trove en Vivo",
      subtitle: "rotaciones y clasificaciones",
      searchPlaceholder: "Buscar jugador por nombre…",
      searchButton: "Buscar",
      refresh: "Actualizar",
      loading: "Cargando Panel de Trove...",
    },
    clock: {
      serverTime: "Hora del Servidor (UTC)",
      day: "Día de Trove",
      dailyReset: "Reinicio diario en",
      weeklyReset: "Reinicio semanal en",
      weekdays: ['Lun', 'Mar', 'Mié', 'Jue', 'Vie', 'Sáb', 'Dom'],
    },
    sidebar: {
      activePlayers: "Jugadores Activos",
      onlineSub: "jugadores conectados ahora",
      live: "EN VIVO",
      chaosWeekly: "Caos Semanal",
      corruxion: "Corruxion",
      fluxion: "Fluxion",
      active: "Activo",
      away: "Ausente",
      voting: "Votación",
      untilReset: "para reinicio",
      leavesIn: "se va en",
      arrivesIn: "llega en",
      windowCloses: "la ventana cierra en",
      nextWindow: "próxima ventana en",
      mysteryItem: "Objeto misterioso",
      noChaos: "Sin datos del Cofre del Caos.",
      noCorruxion: "Sin datos de Corruxion.",
      noFluxion: "Sin datos de Fluxion.",
      footer: "Datos a través de la API Kiwi (aallyn.net).",
      autoRefresh: "Actualización auto cada 30s.",
    },
    badges: {
      unavailable: "No disponible",
      loading: "Cargando",
      live: "En vivo",
      activeInHub: "ACTIVO EN EL HUB",
      away: "AUSENTE",
      updates: "Novedades",
    },
    buffs: {
      title: "Ventajas de Hoy",
      unknown: "Ventaja desconocida",
      unavailable: "La rotación de ventajas no está disponible en este momento.",
    },
    buffNames: {
      "Gathering Day": "Día de Recolección",
      "XP Day": "Día de XP",
      "Mining Day": "Día de Minería",
      "Gem Day": "Día de Gemas",
      "Dragon Day": "Día de Dragones",
      "Loot Day": "Día de Botín",
      "Arena Day": "Día de Arena",
      "Shadow Day": "Día de las Sombras",
      "Chaos Day": "Día del Caos",
    },
    buffDescriptions: {
      "double Radiant Shard Drops": "Fragmentos Radiantes x2",
      "20% Bonus Harvest Chance": "+20% Probabilidad de Cosecha",
      "50% Bonus Ore Chance": "+50% Probabilidad de Minerales",
      "20% Bonus Fish Chance": "+20% Probabilidad de Pesca",
      "Triple Radiant Shard Drops": "Fragmentos Radiantes x3",
      "40% Bonus Harvest Chance": "+40% Probabilidad de Cosecha",
      "100% Bonus Ore Chance": "+100% Probabilidad de Minerales",
      "40% Bonus Fish Chance": "+40% Probabilidad de Pesca",
      "Double Dragon Coin Drops": "Monedas de Dragón x2",
      "Double Star Bar Payouts": "Barra de Estrellas x2",
      "50% Bonus Adventure XP": "+50% XP de Aventura",
      "100% Bonus Adventure XP": "+100% XP de Aventura",
      "Double Gem Dust Drops": "Polvo de Gemas x2",
      "Triple Gem Dust Drops": "Polvo de Gemas x3",
      "Double Chaos Chest Drops": "Cofres del Caos x2",
      "Triple Chaos Chest Drops": "Cofres del Caos x3",
      "Double Shadow Key Fragment Drops": "Fragmentos de Llave de Sombra x2",
      "Triple Shadow Key Fragment Drops": "Fragmentos de Llave de Sombra x3",
    },
    weeklyBonus: {
      title: "Rotación de Bonus Semanal",
      activeNow: "Activo ahora",
      inTime: "en",
      unavailable: "Las ventajas semanales no están disponibles.",
      noData: "Sin datos de rotación semanal.",
      defaultDesc: "Bonus semanal especial activo durante esta semana.",
    },
    biomes: {
      title: "Rotación de Biomas",
      current: "Biomas Actuales",
      next: "Siguiente",
      unknown: "Bioma desconocido",
      noData: "Sin datos de biomas.",
      unavailable: "La rotación de biomas no está disponible.",
    },
    records: {
      title: "Récords de Clasificación",
      troveMastery: "Maestría de Trove",
      geodeMastery: "Maestría de Geoda",
      powerRank: "Rango de Poder",
      unknown: "Desconocido",
      unavailable: "Los récords no están disponibles.",
    },
    luxion: {
      title: "Pruebas de Luxion",
      overviewTitle: "Las Pruebas de Luxion: Información General",
      overviewDesc: "El poderoso dragón Luxion ha dejado el Hub para reclamar su reino, invitando a los trovanos más valientes a probar su fuerza en un evento mensual recurrente: <strong>Las Pruebas de Luxion</strong>. Activo una semana cada mes, desafía a los jugadores a recolectar <strong>Venturine</strong> para fabricar recompensas exclusivas mientras enfrentan duras restricciones.",
      gettingStartedTitle: "Primeros Pasos y Acceso al Reino",
      gettingStartedDesc: "Para unirse, use el portal en la <strong>Guarida de la Luz</strong> en el Hub. Se requiere fabricar un <strong>Pacto de Luxion</strong> usando un <em>Alma Desafortunada</em>, que se puede conseguir con Flux, Créditos o Cubits.",
      progressionTitle: "Progresión y Dificultad",
      progressionDesc: "Dentro de <strong>The Venture Capitol</strong>, Lord Primalux ofrece misiones para derrotar enemigos. Al completarlas, los jugadores eligen su camino:",
      completeTrials: "Completar las Pruebas:",
      completeTrialsDesc: "Cumple el Pacto para recibir una gran recompensa de Venturine y salir tras 10 segundos.",
      progressTrials: "Progresar en las Pruebas:",
      progressTrialsDesc: "No da recompensa inmediata, pero sube de rango el Pacto para aumentar las futuras ganancias.",
      rewardsTitle: "Recompensas y Mecánicas",
      rewardsDesc: "Usa la <strong>Forja de Venturine</strong> para desbloquear coleccionables exclusivos de Luxion.",
      notesTitle: "⚠️ Notas Importantes",
      rule1Title: "Reglas del Reino:",
      rule1Desc: "Velocidad de movimiento y salto limitados, modo construcción deshabilitado y funciones sociales inaccesibles.",
      rule2Title: "Úsalo o Piérdelo:",
      rule2Desc: "Morir resta Venturine de tu inventario. ¡Además, toda la Venturine y Sellos <strong>desaparecen al finalizar el evento</strong>!",
      leavesHubIn: "Sale del Hub en",
      nextArrival: "Próxima llegada",
      scheduleTba: "Horario por confirmar",
      eventCalendarBtn: "Calendario del Evento",
      fastTrialsEndsIn: "Las pruebas rápidas terminan en",
      nextFastTrialsIn: "Próximas pruebas rápidas en"
    },
    trials: {
      whatIsTitle: "¿Qué son las Pruebas Rápidas?",
      whatIsP1: "Las Pruebas Rápidas son una rotación especial donde aumenta la tasa de aparición de los invasores. Esta ventana de 3 horas permite recolectar la mayor cantidad de Venturina posible.",
      whatIsP2: "Cuando esta rotación está activa, los jugadores deben abrir un Portal D13 a un Mundo de Pruebas. Todos los participantes deben estar en el servidor de la UE o de NA; de lo contrario, no podrán unirse al mismo mundo. Luego se quedan AFK en un área plana para recolectar miles de Venturinas durante la rotación de 3 horas.",
      methodTitle: "¿Cuál es el método?",
      methodP1: "Un jugador anuncia la rotación de 3 horas para que otros jugadores puedan unirse al mismo centro que el anfitrión. Luego, cada participante debe abrir un Portal D13 y decidir en qué servidor alojarán (UE o NA).",
      methodP2: "La mayoría de los jugadores suelen poner un temporizador para unirse a los portales al mismo tiempo. Una vez dentro, uno de ellos busca un área plana adecuada donde se llevará a cabo la sesión AFK.",
      methodP3: "Cuando se encuentra el área, colocan un Portal de Origen que permite viajar al resto de jugadores. La sesión suele durar las 3 horas completas, pero cada jugador puede decidir si quedarse hasta el final o salir antes."
    },
    news: {
      title: "Noticias de Trove",
      loading: "Cargando últimas noticias...",
      error: "No se pudieron cargar las noticias.",
      defaultTitle: "Actualización de Trove",
      recent: "Reciente",
    },
    bannerError: "— mostrando los últimos datos disponibles.",
  },

  zh: {
    nav: {
      buffs: "今日增益",
      chaos: "混沌宝箱",
      biomes: "生态群落",
      records: "排行榜纪录",
      player: "玩家查询",
    },
    header: {
      title: "Trove 实时数据看板",
      subtitle: "轮换与排行榜数据",
      searchPlaceholder: "输入玩家名称进行查询…",
      searchButton: "查询",
      refresh: "刷新",
      loading: "正在加载 Trove 看板数据...",
    },
    clock: {
      serverTime: "服务器时间 (UTC)",
      day: "Trove 第几天",
      dailyReset: "每日重置倒计时",
      weeklyReset: "每周重置倒计时",
      weekdays: ['周一', '周二', '周三', '周四', '周五', '周六', '周日'],
    },
    sidebar: {
      activePlayers: "在线玩家",
      onlineSub: "当前全网在线玩家",
      live: "实时",
      chaosWeekly: "本周混沌宝箱",
      corruxion: "腐化龙 (Corruxion)",
      fluxion: "投票龙 (Fluxion)",
      active: "已到来",
      away: "未到达",
      voting: "投票中",
      untilReset: "后重置",
      leavesIn: "离去倒计时",
      arrivesIn: "到来倒计时",
      windowCloses: "窗口关闭倒计时",
      nextWindow: "下一轮窗口倒计时",
      mysteryItem: "神秘物品",
      noChaos: "暂无混沌宝箱数据。",
      noCorruxion: "暂无腐化龙数据。",
      noFluxion: "暂无投票龙数据。",
      footer: "数据来自 Kiwi API (aallyn.net)。",
      autoRefresh: "每 30 秒自动刷新一次。",
    },
    badges: {
      unavailable: "不可用",
      loading: "加载中",
      live: "在线",
      activeInHub: "已在主城中",
      away: "未在主城",
      updates: "更新",
    },
    buffs: {
      title: "今日日常增益",
      unknown: "未知增益",
      unavailable: "增益轮换数据当前不可用。",
    },
    buffNames: {
      "Gathering Day": "采集日",
      "XP Day": "经验日",
      "Mining Day": "挖矿日",
      "Gem Day": "宝石日",
      "Dragon Day": "巨龙日",
      "Loot Day": "掉落日",
      "Arena Day": "竞技场日",
      "Shadow Day": "暗影日",
      "Chaos Day": "混沌日",
    },
    buffDescriptions: {
      "double Radiant Shard Drops": "辉耀碎片掉落翻倍 (2x)",
      "20% Bonus Harvest Chance": "+20% 额外收获几率",
      "50% Bonus Ore Chance": "+50% 额外矿石几率",
      "20% Bonus Fish Chance": "+20% 额外钓鱼几率",
      "Triple Radiant Shard Drops": "辉耀碎片掉落三倍 (3x)",
      "40% Bonus Harvest Chance": "+40% 额外收获几率",
      "100% Bonus Ore Chance": "+100% 额外矿石几率",
      "40% Bonus Fish Chance": "+40% 额外钓鱼几率",
      "Double Dragon Coin Drops": "龙币掉落翻倍 (2x)",
      "Double Star Bar Payouts": "星条充能奖励翻倍 (2x)",
      "50% Bonus Adventure XP": "+50% 额外冒险经验",
      "100% Bonus Adventure XP": "+100% 额外冒险经验",
      "Double Gem Dust Drops": "宝石尘掉落翻倍 (2x)",
      "Triple Gem Dust Drops": "宝石尘掉落三倍 (3x)",
      "Double Chaos Chest Drops": "混沌宝箱掉落翻倍 (2x)",
      "Triple Chaos Chest Drops": "混沌宝箱掉落三倍 (3x)",
      "Double Shadow Key Fragment Drops": "暗影钥匙碎片掉落翻倍 (2x)",
      "Triple Shadow Key Fragment Drops": "暗影钥匙碎片掉落三倍 (3x)",
    },
    weeklyBonus: {
      title: "每周活动增益轮换",
      activeNow: "当前生效中",
      inTime: "距离生效还剩",
      unavailable: "每周增益数据不可用。",
      noData: "暂无每周增益轮换数据。",
      defaultDesc: "本周激活的特殊周常增益。",
    },
    biomes: {
      title: "群落轮换",
      current: "当前群落",
      next: "下一轮群落",
      unknown: "未知群落",
      noData: "暂无群落数据。",
      unavailable: "群落轮换数据暂不可用。",
    },
    records: {
      title: "全服排行榜纪录",
      troveMastery: "Trove 专精",
      geodeMastery: "Geode 专精",
      powerRank: "战斗力等级 (PR)",
      unknown: "未知玩家",
      unavailable: "排行榜纪录暂不可用。",
    },
    luxion: {
      title: "Luxion 的试炼 (Trials of Luxion)",
      overviewTitle: "Luxion 的试炼：模式总览",
      overviewDesc: "巨龙 Luxion 离开了主城去夺回他的领地，仅邀请最勇敢的玩家在每月为期一周的常规事件中证明自己的力量：<strong>Luxion 的试炼</strong>。玩家需要收集<strong>Venturine（砂金石）</strong>以兑换独家限定藏品，同时面临严苛的战斗属性压制及阵亡扣除代币的惩罚。",
      gettingStartedTitle: "新手入门与进入领域",
      gettingStartedDesc: "符合资格的玩家需要通过主城中的<strong>光芒之穴 (Light’s Den)</strong>传送门进入。进入需要使用<em>不幸灵魂 (Unfortunate Soul)</em>在契约登记处制作<strong>Luxion 的契约 (Luxion's Pact)</strong>。",
      progressionTitle: "试炼阶段与难度提升",
      progressionDesc: "在<strong>风投之都 (The Venture Capitol)</strong>内，玩家可以接受 Lord Primalux 的连续任务击败内环、中环与外环的敌人。完成后可自由选择路线：",
      completeTrials: "完成试炼：",
      completeTrialsDesc: "完成契约获得大量 Venturine 奖励并在 10 秒后离开副本。",
      progressTrials: "提升试炼：",
      progressTrialsDesc: "不直接发放奖励，但会将契约升级至更高难度阶位，以增加未来的奖励收益。",
      rewardsTitle: "奖励、机制与风险",
      rewardsDesc: "玩家可以使用<strong>砂金石锻造台 (Venturine Forge)</strong>将代币转换为印章，解锁 Luxion 轮换的收藏宝库。",
      notesTitle: "⚠️ 重要注意事项",
      rule1Title: "领域规则：",
      rule1Desc: "跳跃和移动速度受到上限限制，建造模式和方块破坏被禁用，社交功能（加入/邀请）不可用。",
      rule2Title: "及时兑换，过期清空：",
      rule2Desc: "在领域内死亡会扣除背包中的 Venturine。此外，所有 Venturine、印章和宝箱在<strong>活动结束时将全部消失清空</strong>，请务必在倒计时结束前使用完毕！",
      leavesHubIn: "离开主城倒计时",
      nextArrival: "距离下次到来",
      scheduleTba: "具体排期待定",
      eventCalendarBtn: "活动日程表",
      fastTrialsEndsIn: "狂速试炼结束倒计时",
      nextFastTrialsIn: "下次狂速试炼倒计时"
    },
    trials: {
      whatIsTitle: "什么是狂速试炼？",
      whatIsP1: "狂速试炼是一种特殊的活动轮换机制，期间入侵者的刷新率大幅提高。在这个持续 3 小时的窗口期内，玩家可以尽可能多地收集冒险币 (Venturine)。",
      whatIsP2: "当此轮换激活时，玩家必须开启前往试炼世界的 D13 传送门。所有参与者必须统一在欧洲 (EU) 或北美 (NA) 服务器，否则无法进入同一世界。随后大家在平坦地形处挂机 (AFK)，便可在 3 小时内轻松获取数千冒险币。",
      methodTitle: "具体操作流程是什么？",
      methodP1: "一名玩家发起 3 小时轮换通知，其他玩家进入同一主城集结。之后每位参与者开启 D13 传送门，并统一下注的主机服务器（EU 或 NA）。",
      methodP2: "大家通常会设定倒计时以便在同一时刻同时进入传送门。进入世界后，由一名玩家在地图中寻找适合整队挂机刷怪的平坦地形。",
      methodP3: "找到理想区域后放置回城传送门 (Origin Portal)，其他队员通过传送门快速集合并开启 3 小时 AFK 挂机。玩家可根据个人时间选择全程挂满或提前离场。"
    },
    news: {
      title: "Trove 官方新闻",
      loading: "正在加载最新新闻资讯...",
      error: "无法加载新闻文章。",
      defaultTitle: "Trove 资讯更新",
      recent: "近期发布",
    },
    bannerError: "— 当前显示已缓存的最后数据。",
  }
};