export const depthsSoulsCalcContent = {
  en: {
    tabNormal: "Normal (3 Chests/Run)",
    tabCustom: "Custom Depth",
    isMonday: "Is Monday? (Bonus Drops)",
    isPatron: "Active Patron Status",
    desiredSouls: "Desired Soul of the Depths",
    sparkKeys: "Sparkling Keys Available",
    customDepthLabel: "Starting Delve Depth (170+)",
    calculate: "Calculate",
    errValue: "Please enter a valid desired value.",
    errDepth: "Please enter a valid depth (170+).",
    errNoChests: "No chests available at that depth.",
    soulsKeys: "Souls from Keys",
    soulsChests: "Souls Needed from Chests",
    runsNeeded: "Estimated Runs Needed"
  },
  fr: {
    tabNormal: "Normal (3 Coffres/Run)",
    tabCustom: "Profondeur Personnalisée",
    isMonday: "C'est Lundi ? (Bonus de Drop)",
    isPatron: "Statut Patron Actif",
    desiredSouls: "Âmes des Profondeurs souhaitées",
    sparkKeys: "Clés Étincelantes disponibles",
    customDepthLabel: "Profondeur de départ (170+)",
    calculate: "Calculer",
    errValue: "Veuillez entrer une valeur souhaitée valide.",
    errDepth: "Veuillez entrer une profondeur valide (170+).",
    errNoChests: "Aucun coffre disponible à cette profondeur.",
    soulsKeys: "Âmes obtenues par clés",
    soulsChests: "Âmes requises via coffres",
    runsNeeded: "Runs estimées nécessaires"
  },
  es: {
    tabNormal: "Normal (3 Cofres/Partida)",
    tabCustom: "Profundidad Personalizada",
    isMonday: "¿Es Lunes? (Botín Bonus)",
    isPatron: "Estado de Patrón Activo",
    desiredSouls: "Almas de las Profundidades deseadas",
    sparkKeys: "Llaves Brillantes disponibles",
    customDepthLabel: "Profundidad Inicial (170+)",
    calculate: "Calcular",
    errValue: "Por favor, introduce un valor deseado válido.",
    errDepth: "Por favor, introduce una profundidad válida (170+).",
    errNoChests: "No hay cofres disponibles en esa profundidad.",
    soulsKeys: "Almas obtenidas con llaves",
    soulsChests: "Almas necesarias de cofres",
    runsNeeded: "Partidas estimadas necesarias"
  },
  zh: {
    tabNormal: "普通 (3个宝箱/次)",
    tabCustom: "自定义层数",
    isMonday: "今天是否为周一？(额外掉落)",
    isPatron: "激活会员状态",
    desiredSouls: "目标地窖之魂",
    sparkKeys: "可用闪耀钥匙",
    customDepthLabel: "起始地窖深度 (170+)",
    calculate: "开始计算",
    errValue: "请输入有效的目标数值。",
    errDepth: "请输入有效的深度 (170+)。",
    errNoChests: "该深度下没有可开启的宝箱。",
    soulsKeys: "通过钥匙获得的魂",
    soulsChests: "需要从宝箱获取的魂",
    runsNeeded: "预计所需通关次数"
  }
};