export const starChartContent = {
  en: {
    constellationCombat: 'Constellation of Combat',
    constellationGathering: 'Constellation of Gathering',
    constellationCubesly: 'Constellation of Cubesly',
    recommendedBuilds: 'Recommended Builds ▾',
    clearAll: 'Clear All',
    full: 'Full',
    buildSummary: 'Build Summary',
    copyBuildCode: 'Copy Build Code',
    copied: '✓ Copied',
    pastePlaceholder: 'Paste build code here...',
    load: 'Load',
    nodes: 'Nodes',
    stats: 'Stats',
    abilities: 'Abilities',
    obtainables: 'Obtainables',
    noStats: 'No stats selected.',
    noAbilities: 'No abilities selected.',
    noObtainables: 'No obtainables selected.',
    upgrades: 'Upgrades:',
    titleDesc: '✦ \u00A0Celestial Star Chart Simulator',
    introText: 'Three constellations of stars await. Click any node to select it - ancestors are selected automatically. Double-click a root diamond to select its entire constellation. You may unlock up to 40 nodes per build.',
    credits: 'Credits: BetterTroveTools · AallynReed',
    loreKeyTitle: 'Constellation Key',
    loreKeyDesc: 'Unlocks or resets branches. First 3: 250 Flux at The Celestial. Additional: 130 Credits / 1300 Cubits.',
    loreSphereTitle: 'Celestial Sphere',
    loreSphereDesc: 'Unlocks one specific node. Only 40 Spheres available for 120 slots - plan carefully.',
    loreEchoesTitle: 'Astral Echoes',
    loreEchoesDesc: 'Currency for Spheres. Earned in dungeons/delves (20-50/run), weekly Almanac tome (5000/week), Turtle Shells ×4/week, Despoiled Divinity vendor ×5/day.',
    builds: {
      physLight: 'Physical Damage / Light',
      magicLight: 'Magic Damage / Light',
      magicSpeedLight: 'Magic Damage / Movement Speed / Light',
      physSpeedLight: 'Physical Damage / Movement Speed / Light'
    },
    statNames: {
      "Physical Damage": "Physical Damage",
      "Magic Damage": "Magic Damage",
      "Critical Hit": "Critical Hit",
      "Critical Damage": "Critical Damage",
      "Attack Speed": "Attack Speed",
      "Movement Speed": "Movement Speed",
      "Maximum Health %": "Maximum Health %",
      "Health Regen": "Health Regen",
      "Energy Regen": "Energy Regen",
      "Damage Reduction": "Damage Reduction",
      "Incoming Damage": "Incoming Damage",
      "Outgoing Damage": "Outgoing Damage",
      "Flask Capacity": "Flask Capacity",
      "Magic Find": "Magic Find",
      "Lasermancy": "Lasermancy",
      "Experience Gain": "Experience Gain",
      "Crafting Speed": "Crafting Speed",
      "Jump": "Jump",
      "Stability": "Stability",
      "Light": "Light",
      "Random Flask Emblem": "Random Flask Emblem"
    },
    nodeNames: {
      "Strength": "Strength",
      "Lucky Strikes": "Lucky Strikes",
      "Haste": "Haste",
      "Accuracy": "Accuracy",
      "Leaping and Anti-Knockback": "Leaping and Anti-Knockback",
      "Lucky Strikes 2.0": "Lucky Strikes 2.0",
      "Accuracy, Intellect and Strength": "Accuracy, Intellect and Strength",
      "Accuracy and Heartiness": "Accuracy and Heartiness",
      "Reflection": "Reflection",
      "Reflection 2.0": "Reflection 2.0",
      "Protection": "Protection",
      "Reflection 3.0": "Reflection 3.0",
      "Anti-Knockback": "Anti-Knockback",
      "Intellect": "Intellect",
      "Rage": "Rage",
      "Heartiness": "Heartiness",
      "Rage 1.5": "Rage 1.5",
      "Speed": "Speed",
      "Rage 2.5": "Rage 2.5",
      "Rage 3.0": "Rage 3.0",
      "Weakness": "Weakness",
      "Critical": "Critical",
      "Weakness 1.5": "Weakness 1.5",
      "Luck": "Luck",
      "Shard Searcher": "Shard Searcher",
      "Mining": "Mining",
      "Knowledge": "Knowledge",
      "Knowledge and Luck": "Knowledge and Luck",
      "Knowledge and Accuracy": "Knowledge and Accuracy",
      "Knowledge and Critical": "Knowledge and Critical",
      "Luck and DYI": "Luck and DYI",
      "Alchemy, Heartiness and Leaping": "Alchemy, Heartiness and Leaping",
      "Harvest": "Harvest",
      "Heartiness and Healing": "Heartiness and Healing",
      "Harvest 2.0": "Harvest 2.0",
      "Haste and Critical": "Haste and Critical",
      "Attack": "Attack",
      "Shard Searcher 2.0": "Shard Searcher 2.0",
      "Mining and Heartiness": "Mining and Heartiness",
      "Alchemy": "Alchemy",
      "Healing and Caffeine": "Healing and Caffeine",
      "Mining and Leaps": "Mining and Leaps",
      "Long Reach": "Long Reach",
      "Alchemy and Healing": "Alchemy and Healing",
      "Sundard Flight": "Sundard Flight",
      "Sundered Flight 2.0": "Sundered Flight 2.0",
      "Sundered Flight 3.0": "Sundered Flight 3.0",
      "Long Reach 2.0": "Long Reach 2.0",
      "Long Reach 3.0": "Long Reach 3.0",
      "Heartiness, Haste and Mining": "Heartiness, Haste and Mining",
      "Minor Buffing": "Minor Buffing",
      "Accuracy and Critical": "Accuracy and Critical",
      "Greater Alchemic Power": "Greater Alchemic Power",
      "Greater Alchemic Power 2.0": "Greater Alchemic Power 2.0",
      "Greater Alchemic Power 3.0": "Greater Alchemic Power 3.0",
      "Flask Renewal": "Flask Renewal",
      "Flask Renewal 2.0": "Flask Renewal 2.0",
      "Minor Buffing Always": "Minor Buffing Always",
      "Strength and Intellect": "Strength and Intellect",
      "Healing": "Healing",
      "Draining Kiss": "Draining Kiss",
      "Healing and Heartiness": "Healing and Heartiness",
      "Bounty Hunt Boon": "Bounty Hunt Boon",
      "Bounty Hunt": "Bounty Hunt",
      "Light": "Light",
      "Depths Boon": "Depths Boon",
      "Depths Boon 2.0": "Depths Boon 2.0"
    },
    descriptions: {
      "Within the Strength side of the constellation we try to make Physical based classes tougher than the squishy magic ones.": "Within the Strength side of the constellation we try to make Physical based classes tougher than the squishy magic ones.",
      "Slot machine of extra damage. I like it.": "Slot machine of extra damage. I like it.",
      "Hitting more often means more Critical Hits.": "Hitting more often means more Critical Hits.",
      "A star viewing will lead you to never missing your target's weakness.": "A star viewing will lead you to never missing your target's weakness.",
      "If you get knocked back, you cannot critically hit as much.": "If you get knocked back, you cannot critically hit as much.",
      "Look to the stars for a class that can use lots of critical hit...It's not up there.": "Look to the stars for a class that can use lots of critical hit...It's not up there.",
      "More Strikes then equals less pins to hit.": "More Strikes then equals less pins to hit.",
      "Wow... Magic and Physical Damage with a little Critical Hit... Maybe this should be a Major Star.": "Wow... Magic and Physical Damage with a little Critical Hit... Maybe this should be a Major Star.",
      "Finding this star could grant more then just Health and Critical Hit.": "Finding this star could grant more then just Health and Critical Hit.",
      "Accurately read the stars.": "Accurately read the stars.",
      "They hit you and you hit them back.": "They hit you and you hit them back.",
      "Continue to grow your strength and prove Might is better then brains.": "Continue to grow your strength and prove Might is better then brains.",
      "Reflect even more damage back at your foes.": "Reflect even more damage back at your foes.",
      "Attack and defend is what these stars are about.": "Attack and defend is what these stars are about.",
      "YESSSS... MORE STRENGTH!!!!": "YESSSS... MORE STRENGTH!!!!",
      "Additional shields will be needed for future bosses.": "Additional shields will be needed for future bosses.",
      "Will need to double check numbers to make sure this is not too much strength.": "Will need to double check numbers to make sure this is not too much strength.",
      "This star should help balance melee a little more.": "This star should help balance melee a little more.",
      "Ultimate Strength star is better than a Magic Star.": "Ultimate Strength star is better than a Magic Star.",
      "Not going to push around the brawler.": "Not going to push around the brawler.",
      "Gain greater arcane knowledge to blast your foe down this path.": "Gain greater arcane knowledge to blast your foe down this path.",
      "Star of ARRRRRRRRRRRRRRR!!!!!": "Star of ARRRRRRRRRRRRRRR!!!!!",
      "This star come with a free library card. Somehow that's what increases your damage.": "This star come with a free library card. Somehow that's what increases your damage.",
      "Look at this star trying to make you less squishy over here.": "Look at this star trying to make you less squishy over here.",
      "Wow, mind exploded.": "Wow, mind exploded.",
      "This star's blessing hopes you live a long and healthy life.": "This star's blessing hopes you live a long and healthy life.",
      "Give in to your anger.": "Give in to your anger.",
      "Even though most magic classes have good range, here is some stability so you don't go flying.": "Even though most magic classes have good range, here is some stability so you don't go flying.",
      "Little bit of speed for slow magic classes.": "Little bit of speed for slow magic classes.",
      "Unlimited Magic... unless you run out of energy regen.": "Unlimited Magic... unless you run out of energy regen.",
      "Oops, didn't I mean to make this a health star?": "Oops, didn't I mean to make this a health star?",
      "Kind of odd that the intellect tree has a rage mechanic...I guess it's a nerd rage.": "Kind of odd that the intellect tree has a rage mechanic...I guess it's a nerd rage.",
      "Ahhh this is where I put that Health Star.": "Ahhh this is where I put that Health Star.",
      "The final star spell is ready. Are you ready to cast it?": "The final star spell is ready. Are you ready to cast it?",
      "This Star represents our home which was destroyed by the Void.": "This Star represents our home which was destroyed by the Void.",
      "You have found the Weakness, now keep on attacking.": "You have found the Weakness, now keep on attacking.",
      "Stop being so critical.": "Stop being so critical.",
      "A star all about seeing overly sized numbers appearing.": "A star all about seeing overly sized numbers appearing.",
      "A Critical Hit!": "A Critical Hit!",
      "Search the lands for greater goods.": "Search the lands for greater goods.",
      "Guides you to finding even more useful ore.": "Guides you to finding even more useful ore.",
      "Show how to have more mastery over your laser.": "Show how to have more mastery over your laser.",
      "Knowledge is power - with this you will gain even more.": "Knowledge is power - with this you will gain even more.",
      "With a little luck and brains you can do anything.": "With a little luck and brains you can do anything.",
      "See the weakness of your enemies and know how to exploit it.": "See the weakness of your enemies and know how to exploit it.",
      "A star too small to be a planet but hurts too much to accept the truth.": "A star too small to be a planet but hurts too much to accept the truth.",
      "So glad to see you all the way out here, the star focuses on finding better gear.": "So glad to see you all the way out here, the star focuses on finding better gear.",
      "Speeds up crafting...I know I would love that.": "Speeds up crafting...I know I would love that.",
      "Leap for the stars!!!!": "Leap for the stars!!!!",
      "Grow even more crops.": "Grow even more crops.",
      "Grants the feeling of vigor you get from eating a large meal.": "Grants the feeling of vigor you get from eating a large meal.",
      "Ultimate Harvest upgrade for any gathering min/maxer.": "Ultimate Harvest upgrade for any gathering min/maxer.",
      "A reward for gathering - hitting hard and fast.": "A reward for gathering - hitting hard and fast.",
      "When searching for items, you have gained greater defense.": "When searching for items, you have gained greater defense.",
      "Working on mining has given you a little more edge.": "Working on mining has given you a little more edge.",
      "Lots more shiny ore to collect.": "Lots more shiny ore to collect.",
      "This is the end of the path... was it worth it?": "This is the end of the path... was it worth it?",
      "An extra flask here and there, soon you'll be invincible...": "An extra flask here and there, soon you'll be invincible...",
      "A little bit of coffee will heal anyone.": "A little bit of coffee will heal anyone.",
      "Mine with ease of being able to jump a little more.": "Mine with ease of being able to jump a little more.",
      "When mounted, Harvest at short range.": "When mounted, Harvest at short range.",
      "Gain healing and the ability to heal more. Sounds good, right?": "Gain healing and the ability to heal more. Sounds good, right?",
      "Fly free you fools in the Sundered Uplands.": "Fly free you fools in the Sundered Uplands.",
      "Fly even faster.": "Fly even faster.",
      "I am like a dragon, I only fly away.": "I am like a dragon, I only fly away.",
      "This star gains the boon of health and mining.": "This star gains the boon of health and mining.",
      "When mounted, Harvest at medium range.": "When mounted, Harvest at medium range.",
      "After searching the stars, you have gained increased magic.": "After searching the stars, you have gained increased magic.",
      "Hee Hee this star gives more health.": "Hee Hee this star gives more health.",
      "When mounted Harvest at Loooooooooooonger range. \nGrants a Balefire Dragon Egg Fragment when unlocked.": "When mounted Harvest at Loooooooooooonger range. \nGrants a Balefire Dragon Egg Fragment when unlocked.",
      "Exploring and armoring up.": "Exploring and armoring up.",
      "Seeing the final frontier has left you tough.": "Seeing the final frontier has left you tough.",
      "Intense searching has led you to greater speed and adaptability.": "Intense searching has led you to greater speed and adaptability.",
      "Extra flasks are always good.": "Extra flasks are always good.",
      "Magic power from gathering so much knowledge.": "Magic power from gathering so much knowledge.",
      "You did so much Mining it improved your Physical Damage. Noice.": "You did so much Mining it improved your Physical Damage. Noice.",
      "Increased experience gain is always good.": "Increased experience gain is always good.",
      "Little bit of luck on this side of the stars as well.": "Little bit of luck on this side of the stars as well.",
      "Gathering stars together has increased your strength.": "Gathering stars together has increased your strength.",
      "A branch of a constellation related to Flasks? What could go wrong?": "A branch of a constellation related to Flasks? What could go wrong?",
      "Random buffs are always great because they are buffs.": "Random buffs are always great because they are buffs.",
      "Real Critting is more about following your heart than following a build.": "Real Critting is more about following your heart than following a build.",
      "This should help you jump and not get thrown across the room in delves.": "This should help you jump and not get thrown across the room in delves.",
      "Why are flasks so OP... here is a random one.": "Why are flasks so OP... here is a random one.",
      "More random effects. MOOOOORREEEEE!!!!": "More random effects. MOOOOORREEEEE!!!!",
      "A higher chance to get additional effects is always good.": "A higher chance to get additional effects is always good.",
      "This shooting star is so fast it teaches trovians to hit faster.": "This shooting star is so fast it teaches trovians to hit faster.",
      "Little bit of speed to help you in the world.": "Little bit of speed to help you in the world.",
      "Fighting throughout this Trovian world has given you the intellect to randomly recharge flasks.": "Fighting throughout this Trovian world has given you the intellect to randomly recharge flasks.",
      "When visiting the final frontier, it's always good to have speed.": "When visiting the final frontier, it's always good to have speed.",
      "Star of health bless us with more health please.": "Star of health bless us with more health please.",
      "Attack speed is all some classes need.": "Attack speed is all some classes need.",
      "A Blessing of bountiful flasks... I really hope this is not too OP... Maybe I need to nerf Death-Defying...": "A Blessing of bountiful flasks... I really hope this is not too OP... Maybe I need to nerf Death-Defying...",
      "Now that flasks are powered up, heres a few more.": "Now that flasks are powered up, heres a few more.",
      "So Many Flasks!!!!!": "So Many Flasks!!!!!",
      "You get a buff and you get a buff, everybody gets a buff.": "You get a buff and you get a buff, everybody gets a buff.",
      "Drinking too many flasks has made the random buffs gained from them stick.": "Drinking too many flasks has made the random buffs gained from them stick.",
      "The shield may be just as important as DPS number charts.": "The shield may be just as important as DPS number charts.",
      "Moooooooooooreeeeeeeee Healing PLEASE!!!": "Moooooooooooreeeeeeeee Healing PLEASE!!!",
      "Star of speed give me swiftness to strike my foes.": "Star of speed give me swiftness to strike my foes.",
      "Drain health from your enemies.": "Drain health from your enemies.",
      "Attacks so fast you can not even animate fast enough.": "Attacks so fast you can not even animate fast enough.",
      "In this constellation of dungeon seeking we greet thee with more health.": "In this constellation of dungeon seeking we greet thee with more health.",
      "With faster attack and higher life leech you may someday be invincible.": "With faster attack and higher life leech you may someday be invincible.",
      "Two damage types, maybe someday we will search the stars and find the 3rd one.": "Two damage types, maybe someday we will search the stars and find the 3rd one.",
      "Speed through the stars for greater power.": "Speed through the stars for greater power.",
      "One day it will be super important to have a lot of this. Wink Wink": "One day it will be super important to have a lot of this. Wink Wink",
      "Fly, you fools, Fly to the end of that Delve.": "Fly, you fools, Fly to the end of that Delve.",
      "Hunting enemies now grants you boons.": "Hunting enemies now grants you boons.",
      "Looking up at the stars has granted additional buff time.": "Looking up at the stars has granted additional buff time.",
      "Grant me the true power of the stars. May I destroy the darkness of the cosmos.": "Grant me the true power of the stars. May I destroy the darkness of the cosmos.",
      "Wink Wink...": "Wink Wink...",
      "Jump up without being pushed around by bullies.": "Jump up without being pushed around by bullies.",
      "Looking to the stars to decide how to increase those damage numbers.": "Looking to the stars to decide how to increase those damage numbers.",
      "Greater shining light to destroy the dark.": "Greater shining light to destroy the dark.",
      "Oops, did I leave a flask over on this side of the cosmos.": "Oops, did I leave a flask over on this side of the cosmos.",
      "Delving just got a little bit easier.": "Delving just got a little bit easier.",
      "A little more time to the boon you just got.": "A little more time to the boon you just got.",
      "Look up at the sky one night and see the lights above.": "Look up at the sky one night and see the lights above."
    },
    abilitiesMap: {
      "5% chance when critical hitting to increase Critical Hit by 20% for 10 seconds.": "5% chance when critical hitting to increase Critical Hit by 20% for 10 seconds.",
      "10% chance when critical hitting to increase Critical Hit by 30% for 10 seconds.": "10% chance when critical hitting to increase Critical Hit by 30% for 10 seconds.",
      "When taking damage, you have a 10% chance to gain a 20% reflect shield for 10 seconds. Has a 1 minute cooldown.": "When taking damage, you have a 10% chance to gain a 20% reflect shield for 10 seconds. Has a 1 minute cooldown.",
      "When taking damage, you have a 20% chance to gain a 30% reflect shield for 10 seconds. Has a 1 minute cooldown.": "When taking damage, you have a 20% chance to gain a 30% reflect shield for 10 seconds. Has a 1 minute cooldown.",
      "When taking damage, you have a 30% chance to gain a 45% reflect shield and 30% damage reduction for 10 seconds. Has a 1 minute cooldown.": "When taking damage, you have a 30% chance to gain a 45% reflect shield and 30% damage reduction for 10 seconds. Has a 1 minute cooldown.",
      "When dropping below 30% health, gain a 6% Outgoing damage buff and 10% Attack Speed for 10 seconds. 120 second cooldown.": "When dropping below 30% health, gain a 6% Outgoing damage buff and 10% Attack Speed for 10 seconds. 120 second cooldown.",
      "When dropping below 40% health, gain a 8% Outgoing damage buff and 10% Attack Speed for 10 seconds. 120 second cooldown.": "When dropping below 40% health, gain a 8% Outgoing damage buff and 10% Attack Speed for 10 seconds. 120 second cooldown.",
      "When dropping below 45% health, gain a 10% Outgoing damage buff and 10% Attack Speed for 10 seconds. 120 second cooldown.": "When dropping below 45% health, gain a 10% Outgoing damage buff and 10% Attack Speed for 10 seconds. 120 second cooldown.",
      "When dropping below 45% health, gain a 12% Outgoing damage buff and 10% Attack Speed for 15 seconds. 120 second cooldown.": "When dropping below 45% health, gain a 12% Outgoing damage buff and 10% Attack Speed for 15 seconds. 120 second cooldown.",
      "5% chance when critical hitting to increase Critical Damage by 15% for 10 seconds.": "5% chance when critical hitting to increase Critical Damage by 15% for 10 seconds.",
      "10% chance when critical hitting to increases Critical Damage by 25% for 10 seconds.": "10% chance when critical hitting to increases Critical Damage by 25% for 10 seconds.",
      "Increases amount of ore mined by 10%. ": "Increases amount of ore mined by 10%. ",
      "Increases amount of ore mined by 15%. ": "Increases amount of ore mined by 15%. ",
      "Increases experience gain by 5%. ": "Increases experience gain by 5%. ",
      "Increases harvesting by 10%. ": "Increases harvesting by 10%. ",
      "Increases harvesting by 15%. ": "Increases harvesting by 15%. ",
      "Slightly increases gathering range when mounted. ": "Slightly increases gathering range when mounted. ",
      "Moderately increases gathering range when mounted. ": "Moderately increases gathering range when mounted. ",
      "Greatly increases gathering range when mounted.": "Greatly increases gathering range when mounted.",
      "Reduces glide reduction in Uber 7 of Sundered Uplands.": "Reduces glide reduction in Uber 7 of Sundered Uplands.",
      "Reduces glide reduction in Uber 10 and lower of Sundered Uplands.": "Reduces glide reduction in Uber 10 and lower of Sundered Uplands.",
      "Reduces glide reduction in all Sundered Uplands.": "Reduces glide reduction in all Sundered Uplands.",
      "50% chance when using a Flask to gain either a 25% Bonus Damage, 200 Stability, or 200% Bonus Health Regen.": "50% chance when using a Flask to gain either a 25% Bonus Damage, 200 Stability, or 200% Bonus Health Regen.",
      "100% chance when using a Flask to gain either a 25% Bonus Damage, 200 Stability, or 200% Bonus Health Regen.": "100% chance when using a Flask to gain either a 25% Bonus Damage, 200 Stability, or 200% Bonus Health Regen.",
      "10% chance to gain a random emblem effect when using a flask.": "10% chance to gain a random emblem effect when using a flask.",
      "5% chance to gain a flask charge when using a Flask.": "5% chance to gain a flask charge when using a Flask.",
      "10% chance to gain a flask charge when using a Flask.": "10% chance to gain a flask charge when using a Flask.",
      "Damaging enemies grants 10% Life Leech.": "Damaging enemies grants 10% Life Leech.",
      "Damaging enemies grants 20% Life Leech. ": "Damaging enemies grants 20% Life Leech. ",
      "After defeating a Sundered Uplands 5 Star Boss, gain 10% increased Physical and Magic Damage for 4 hours.": "After defeating a Sundered Uplands 5 Star Boss, gain 10% increased Physical and Magic Damage for 4 hours.",
      "After defeating a Sundered Uplands 5 Star Boss, gain 15% increased Physical and Magic Damage for 4 hours.": "After defeating a Sundered Uplands 5 Star Boss, gain 15% increased Physical and Magic Damage for 4 hours.",
      "After defeating a delve boss, gain 20% damage reduction for 30 minutes. ": "After defeating a delve boss, gain 20% damage reduction for 30 minutes. ",
      "Increases the Depths boon damage reduction to 25% and duration to 1 hour.": "Increases the Depths boon damage reduction to 25% and duration to 1 hour."
    },
    obtainablesMap: {
      "Grants a Balefire Dragon Egg Fragment when unlocked.": "Grants a Balefire Dragon Egg Fragment when unlocked.",
      "Grants a Caprian Dragon Egg Fragment when upgrading.": "Grants a Caprian Dragon Egg Fragment when upgrading.",
      "Grants a Caprian Dragon Egg Fragment when upgrading": "Grants a Caprian Dragon Egg Fragment when upgrading",
      "Grants Ursa Minor when upgrading": "Grants Ursa Minor when upgrading",
      "Grants Ursa Major when upgrading": "Grants Ursa Major when upgrading",
      "Grants Staruable when upgrading": "Grants Staruable when upgrading",
      "Grants Star Dust when upgrading": "Grants Star Dust when upgrading",
      "Grants Star Sebastian when upgrading": "Grants Star Sebastian when upgrading",
      "Grants Charter's Chair when upgrading": "Grants Charter's Chair when upgrading",
      "Grants Starry Skyfire when upgrading": "Grants Starry Skyfire when upgrading",
      "Grants Scorpius when upgrading": "Grants Scorpius when upgrading"
    }
  },
  fr: {
    constellationCombat: 'Constellation du Combat',
    constellationGathering: 'Constellation de la Récolte',
    constellationCubesly: 'Constellation de Cubesly',
    recommendedBuilds: 'Builds Recommandés ▾',
    clearAll: 'Tout Effacer',
    full: 'Plein',
    buildSummary: 'Résumé du Build',
    copyBuildCode: 'Copier le Code',
    copied: '✓ Copié',
    pastePlaceholder: 'Collez le code du build...',
    load: 'Charger',
    nodes: 'Nœuds',
    stats: 'Statistiques',
    abilities: 'Compétences',
    obtainables: 'Objets Obtenables',
    noStats: 'Aucune statistique sélectionnée.',
    noAbilities: 'Aucune compétence sélectionnée.',
    noObtainables: 'Aucun objet sélectionné.',
    upgrades: 'Améliorations :',
    titleDesc: '✦ \u00A0Simulateur de Carte Céleste',
    introText: 'Trois constellations d\'étoiles vous attendent. Cliquez sur un nœud pour le sélectionner. Double-cliquez sur le diamant d\'origine pour sélectionner toute sa constellation. Vous pouvez débloquer jusqu\'à 40 nœuds par build.',
    credits: 'Crédits : BetterTroveTools · AallynReed',
    loreKeyTitle: 'Clé de Constellation',
    loreKeyDesc: 'Débloque ou réinitialise les branches. Les 3 premières : 250 Flux au Céleste.',
    loreSphereTitle: 'Sphère Céleste',
    loreSphereDesc: 'Débloque un nœud spécifique. Seulement 40 Sphères disponibles pour 120 emplacements.',
    loreEchoesTitle: 'Échos Astraux',
    loreEchoesDesc: 'Monnaie pour les Sphères. S\'obtient dans les donjons/delves, le tome hebdomadaire et les vendeurs.',
    builds: {
      physLight: 'Dégâts Physiques / Lumière',
      magicLight: 'Dégâts Magiques / Lumière',
      magicSpeedLight: 'Dégâts Magiques / Vitesse de Mouvement / Lumière',
      physSpeedLight: 'Dégâts Physiques / Vitesse de Mouvement / Lumière'
    },
    statNames: {
      "Physical Damage": "Dégâts Physiques",
      "Magic Damage": "Dégâts Magiques",
      "Critical Hit": "Coup Critique",
      "Critical Damage": "Dégâts Critiques",
      "Attack Speed": "Vitesse d'Attaque",
      "Movement Speed": "Vitesse de Déplacement",
      "Maximum Health %": "Santé Maximale %",
      "Health Regen": "Régénération de Santé",
      "Energy Regen": "Régénération d'Énergie",
      "Damage Reduction": "Réduction de Dégâts",
      "Incoming Damage": "Dégâts Subis",
      "Outgoing Damage": "Dégâts Infligés",
      "Flask Capacity": "Capacité de Fioles",
      "Magic Find": "Trouvaille Magique",
      "Lasermancy": "Lasermancie",
      "Experience Gain": "Gain d'Expérience",
      "Crafting Speed": "Vitesse de Craft",
      "Jump": "Saut",
      "Stability": "Stabilité",
      "Light": "Lumière",
      "Random Flask Emblem": "Emblème de Fiole Aléatoire"
    },
    nodeNames: {
      "Strength": "Force",
      "Lucky Strikes": "Frappes Chanceuses",
      "Haste": "Hâte",
      "Accuracy": "Précision",
      "Leaping and Anti-Knockback": "Saut & Anti-Repousse",
      "Lucky Strikes 2.0": "Frappes Chanceuses 2.0",
      "Accuracy, Intellect and Strength": "Précision, Intellect & Force",
      "Accuracy and Heartiness": "Précision & Vigueur",
      "Reflection": "Réflection",
      "Reflection 2.0": "Réflection 2.0",
      "Protection": "Protection",
      "Reflection 3.0": "Réflection 3.0",
      "Anti-Knockback": "Anti-Repousse",
      "Intellect": "Intellect",
      "Rage": "Rage",
      "Heartiness": "Vigueur",
      "Rage 1.5": "Rage 1.5",
      "Speed": "Vitesse",
      "Rage 2.5": "Rage 2.5",
      "Rage 3.0": "Rage 3.0",
      "Weakness": "Faiblesse",
      "Critical": "Critique",
      "Weakness 1.5": "Faiblesse 1.5",
      "Luck": "Chance",
      "Shard Searcher": "Chercheur d'Éclats",
      "Mining": "Minage",
      "Knowledge": "Savoir",
      "Knowledge and Luck": "Savoir & Chance",
      "Knowledge and Accuracy": "Savoir & Précision",
      "Knowledge and Critical": "Savoir & Critique",
      "Luck and DYI": "Chance & Bricolage",
      "Alchemy, Heartiness and Leaping": "Alchimie, Vigueur & Saut",
      "Harvest": "Récolte",
      "Heartiness and Healing": "Vigueur & Soin",
      "Harvest 2.0": "Récolte 2.0",
      "Haste and Critical": "Hâte & Critique",
      "Attack": "Attaque",
      "Shard Searcher 2.0": "Chercheur d'Éclats 2.0",
      "Mining and Heartiness": "Minage & Vigueur",
      "Alchemy": "Alchimie",
      "Healing and Caffeine": "Soin & Caféine",
      "Mining and Leaps": "Minage & Sauts",
      "Long Reach": "Portée Allongée",
      "Alchemy and Healing": "Alchimie & Soin",
      "Sundard Flight": "Vol Céleste",
      "Sundered Flight 2.0": "Vol Céleste 2.0",
      "Sundered Flight 3.0": "Vol Céleste 3.0",
      "Long Reach 2.0": "Portée Allongée 2.0",
      "Long Reach 3.0": "Portée Allongée 3.0",
      "Heartiness, Haste and Mining": "Vigueur, Hâte & Minage",
      "Minor Buffing": "Buff Mineur",
      "Accuracy and Critical": "Précision & Critique",
      "Greater Alchemic Power": "Grand Pouvoir Alchimique",
      "Greater Alchemic Power 2.0": "Grand Pouvoir Alchimique 2.0",
      "Greater Alchemic Power 3.0": "Grand Pouvoir Alchimique 3.0",
      "Flask Renewal": "Renouveau de Fiole",
      "Flask Renewal 2.0": "Renouveau de Fiole 2.0",
      "Minor Buffing Always": "Buff Mineur Permanent",
      "Strength and Intellect": "Force & Intellect",
      "Healing": "Soin",
      "Draining Kiss": "Baiser Drainant",
      "Healing and Heartiness": "Soin & Vigueur",
      "Bounty Hunt Boon": "Bonus de Chasse",
      "Bounty Hunt": "Chasse à la Prime",
      "Light": "Lumière",
      "Depths Boon": "Bonus des Profondeurs",
      "Depths Boon 2.0": "Bonus des Profondeurs 2.0"
    },
    descriptions: {
      "Within the Strength side of the constellation we try to make Physical based classes tougher than the squishy magic ones.": "Côté Force, nous rendons les classes physiques plus solides que les magiques.",
      "Slot machine of extra damage. I like it.": "Machine à sous de dégâts supplémentaires.",
      "Hitting more often means more Critical Hits.": "Frapper plus souvent signifie plus de coups critiques.",
      "A star viewing will lead you to never missing your target's weakness.": "Contempler cette étoile vous évitera de rater le point faible de votre cible.",
      "If you get knocked back, you cannot critically hit as much.": "Si vous êtes repoussé, vous frappez moins de coups critiques.",
      "Look to the stars for a class that can use lots of critical hit...It's not up there.": "Cherchez une classe spécialisée en coups critiques... Elle n'est pas là-haut.",
      "More Strikes then equals less pins to hit.": "Plus de frappes signifie moins de cibles à toucher.",
      "Wow... Magic and Physical Damage with a little Critical Hit... Maybe this should be a Major Star.": "Dégâts magiques et physiques avec du coup critique... Une vraie étoile majeure !",
      "Finding this star could grant more then just Health and Critical Hit.": "Trouver cette étoile apporte plus que de la santé et du coup critique.",
      "Accurately read the stars.": "Lisez attentivement les étoiles.",
      "They hit you and you hit them back.": "Ils vous frappent, vous ripostez.",
      "Continue to grow your strength and prove Might is better then brains.": "Prouvez que la force brute l'emporte sur l'esprit.",
      "Reflect even more damage back at your foes.": "Renvoyez encore plus de dégâts à vos ennemis.",
      "Attack and defend is what these stars are about.": "Attaque et défense sont les maîtres-mots de ces étoiles.",
      "YESSSS... MORE STRENGTH!!!!": "OUI ! ENCORE PLUS DE FORCE !",
      "Additional shields will be needed for future bosses.": "Des boucliers supplémentaires seront requis pour les futurs boss.",
      "Will need to double check numbers to make sure this is not too much strength.": "Vérifions que cette force n'est pas trop démesurée.",
      "This star should help balance melee a little more.": "Cette étoile aide à rééquilibrer le combat au corps à corps.",
      "Ultimate Strength star is better than a Magic Star.": "L'étoile de force ultime surpasse une étoile magique.",
      "Not going to push around the brawler.": "Personne ne bousculera ce combattant.",
      "Gain greater arcane knowledge to blast your foe down this path.": "Obtenez un savoir arcane supérieur pour anéantir vos ennemis.",
      "Star of ARRRRRRRRRRRRRRR!!!!!": "Étoile du rugissement de rage !",
      "This star come with a free library card. Somehow that's what increases your damage.": "Cette étoile inclut une carte de bibliothèque gratuite !",
      "Look at this star trying to make you less squishy over here.": "Une étoile dédiée à renforcer votre résistance.",
      "Wow, mind exploded.": "Un savoir à en couper le souffle.",
      "This star's blessing hopes you live a long and healthy life.": "La bénédiction de cette étoile vous souhaite une longue vie.",
      "Give in to your anger.": "Cédez à votre colère.",
      "Even though most magic classes have good range, here is some stability so you don't go flying.": "De la stabilité pour éviter de voler sous les coups.",
      "Little bit of speed for slow magic classes.": "Un peu de vitesse pour les classes magiques lentes.",
      "Unlimited Magic... unless you run out of energy regen.": "Magie illimitée... tant que votre énergie se régénère.",
      "Oops, didn't I mean to make this a health star?": "N'était-ce pas censé être une étoile de santé ?",
      "Kind of odd that the intellect tree has a rage mechanic...I guess it's a nerd rage.": "Une mécanique de rage dans l'arbre d'intellect... Une rage de savant !",
      "Ahhh this is where I put that Health Star.": "Ah ! Voilà où était passée cette étoile de santé.",
      "The final star spell is ready. Are you ready to cast it?": "Le sort ultime est prêt. Êtes-vous prêt à l'invoquer ?",
      "This Star represents our home which was destroyed by the Void.": "Cette étoile représente notre foyer détruit par le Vide.",
      "You have found the Weakness, now keep on attacking.": "Vous avez trouvé la faiblesse, continuez l'attaque.",
      "Stop being so critical.": "Ne soyez pas si critique !",
      "A star all about seeing overly sized numbers appearing.": "Une étoile pour afficher des chiffres de dégâts géants.",
      "A Critical Hit!": "Un Coup Critique !",
      "Search the lands for greater goods.": "Parcourez les terres à la recherche de trésors.",
      "Guides you to finding even more useful ore.": "Vous guide vers des minerais encore plus utiles.",
      "Show how to have more mastery over your laser.": "Maîtrisez encore mieux votre laser.",
      "Knowledge is power - with this you will gain even more.": "Le savoir est une force : apprenez encore plus.",
      "With a little luck and brains you can do anything.": "Avec de la chance et de la réflexion, tout est possible.",
      "See the weakness of your enemies and know how to exploit it.": "Repérez les faiblesses ennemies et exploitez-les.",
      "A star too small to be a planet but hurts too much to accept the truth.": "Une étoile minuscule mais redoutablement puissante.",
      "So glad to see you all the way out here, the star focuses on finding better gear.": "Ravi de vous voir ici : cette étoile aide à trouver du meilleur équipement.",
      "Speeds up crafting...I know I would love that.": "Accélère la fabrication de vos objets.",
      "Leap for the stars!!!!": "Sautez vers les étoiles !",
      "Grow even more crops.": "Faites pousser encore plus de récoltes.",
      "Grants the feeling of vigor you get from eating a large meal.": "La sensation de vigueur d'un festin copieux.",
      "Ultimate Harvest upgrade for any gathering min/maxer.": "L'amélioration de récolte ultime pour les passionnés.",
      "A reward for gathering - hitting hard and fast.": "Récompense de récolte : frapper fort et vite.",
      "When searching for items, you have gained greater defense.": "En cherchant des objets, votre défense augmente.",
      "Working on mining has given you a little more edge.": "Le travail minier vous donne un avantage au combat.",
      "Lots more shiny ore to collect.": "Encore plus de minerais brillants à collecter.",
      "This is the end of the path... was it worth it?": "C'est la fin du chemin... Cela en valait-il la peine ?",
      "An extra flask here and there, soon you'll be invincible...": "Une fiole de plus par-ci par-là pour devenir invincible...",
      "A little bit of coffee will heal anyone.": "Un bon café soigne n'importe qui.",
      "Mine with ease of being able to jump a little more.": "Minez facilement tout en sautant plus haut.",
      "When mounted, Harvest at short range.": "À monture, récoltez à courte portée.",
      "Gain healing and the ability to heal more. Sounds good, right?": "Soignez-vous et augmentez vos capacités de soin.",
      "Fly free you fools in the Sundered Uplands.": "Volez librement dans les Sundered Uplands.",
      "Fly even faster.": "Volez encore plus vite.",
      "I am like a dragon, I only fly away.": "Tel un dragon, je m'envole au loin.",
      "This star gains the boon of health and mining.": "Cette étoile offre santé et compétences de minage.",
      "When mounted, Harvest at medium range.": "À monture, récoltez à moyenne portée.",
      "After searching the stars, you have gained increased magic.": "En explorant les étoiles, votre magie augmente.",
      "Hee Hee this star gives more health.": "Hihi ! Cette étoile donne encore plus de santé.",
      "When mounted Harvest at Loooooooooooonger range. \nGrants a Balefire Dragon Egg Fragment when unlocked.": "À monture, récoltez à très longue portée.",
      "Exploring and armoring up.": "Explorez et renforcez votre armure.",
      "Seeing the final frontier has left you tough.": "Explorer la frontière ultime vous a rendu endurci.",
      "Intense searching has led you to greater speed and adaptability.": "Vos recherches vous apportent vitesse et adaptabilité.",
      "Extra flasks are always good.": "Des fioles supplémentaires sont toujours bienvenues.",
      "Magic power from gathering so much knowledge.": "Puissance magique accumulée par le savoir.",
      "You did so much Mining it improved your Physical Damage. Noice.": "Tant de minage a renforcé vos dégâts physiques !",
      "Increased experience gain is always good.": "Un gain d'expérience accru est toujours utile.",
      "Little bit of luck on this side of the stars as well.": "Un peu de chance supplémentaire de ce côté des étoiles.",
      "Gathering stars together has increased your strength.": "Rassembler les étoiles a décuplé votre force.",
      "A branch of a constellation related to Flasks? What could go wrong?": "Une branche liée aux fioles ? Que pourrait-il arriver ?",
      "Random buffs are always great because they are buffs.": "Des bonus aléatoires restent d'excellents bonus.",
      "Real Critting is more about following your heart than following a build.": "Réussir ses critiques, c'est suivre son cœur.",
      "This should help you jump and not get thrown across the room in delves.": "Aide à sauter sans se faire projeter dans les delves.",
      "Why are flasks so OP... here is a random one.": "Pourquoi les fioles sont-elles si puissantes ?",
      "More random effects. MOOOOORREEEEE!!!!": "Encore plus d'effets aléatoires !",
      "A higher chance to get additional effects is always good.": "Plus de chances d'obtenir des effets supplémentaires.",
      "This shooting star is so fast it teaches trovians to hit faster.": "Une étoile filante qui vous apprend à frapper plus vite.",
      "Little bit of speed to help you in the world.": "Un peu de vitesse pour explorer le monde.",
      "Fighting throughout this Trovian world has given you the intellect to randomly recharge flasks.": "Combattre vous permet de recharger vos fioles aléatoirement.",
      "When visiting the final frontier, it's always good to have speed.": "La vitesse est essentielle pour l'exploration ultime.",
      "Star of health bless us with more health please.": "Étoile de santé, accorde-nous plus de vie !",
      "Attack speed is all some classes need.": "La vitesse d'attaque est la clé de certaines classes.",
      "A Blessing of bountiful flasks... I really hope this is not too OP... Maybe I need to nerf Death-Defying...": "Bénédiction de fioles généreuses...",
      "Now that flasks are powered up, heres a few more.": "Maintenant que les fioles sont puissantes, en voici d'autres.",
      "So Many Flasks!!!!!": "Tant de fioles !",
      "You get a buff and you get a buff, everybody gets a buff.": "Des bonus pour tout le monde !",
      "Drinking too many flasks has made the random buffs gained from them stick.": "Consommer des fioles prolonge leurs effets.",
      "The shield may be just as important as DPS number charts.": "Le bouclier est aussi crucial que vos dégâts.",
      "Moooooooooooreeeeeeeee Healing PLEASE!!!": "Encore plus de soins, s'il vous plaît !",
      "Star of speed give me swiftness to strike my foes.": "Étoile de vitesse, donne-moi la rapidité.",
      "Drain health from your enemies.": "Drainez la santé de vos ennemis.",
      "Attacks so fast you can not even animate fast enough.": "Des attaques trop rapides pour être animées !",
      "In this constellation of dungeon seeking we greet thee with more health.": "Dans cette constellation, nous vous offrons plus de santé.",
      "With faster attack and higher life leech you may someday be invincible.": "Attaques rapides et vol de vie vous rendent invincible.",
      "Two damage types, maybe someday we will search the stars and find the 3rd one.": "Deux types de dégâts aujourd'hui, un troisième bientôt ?",
      "Speed through the stars for greater power.": "Traversez les étoiles pour plus de puissance.",
      "One day it will be super important to have a lot of this. Wink Wink": "Un jour, cette statistique sera cruciale !",
      "Fly, you fools, Fly to the end of that Delve.": "Volez jusqu'au fond de ce Delve !",
      "Hunting enemies now grants you boons.": "Chasser les ennemis vous octroie des bénédictions.",
      "Looking up at the stars has granted additional buff time.": "Observer les étoiles prolonge vos bonus.",
      "Grant me the true power of the stars. May I destroy the darkness of the cosmos.": "Accordez-moi la vraie puissance céleste.",
      "Wink Wink...": "Clin d'œil...",
      "Jump up without being pushed around by bullies.": "Sautez sans vous faire bousculer.",
      "Looking to the stars to decide how to increase those damage numbers.": "Consultez les étoiles pour augmenter vos dégâts.",
      "Greater shining light to destroy the dark.": "Une lumière éclatante pour détruire les ténèbres.",
      "Oops, did I leave a flask over on this side of the cosmos.": "Oups, ai-je oublié une fiole de ce côté ?",
      "Delving just got a little bit easier.": "L'exploration des Delves devient un peu plus facile.",
      "A little more time to the boon you just got.": "Prolonge la durée du bonus obtenu.",
      "Look up at the sky one night and see the lights above.": "Regardez le ciel nocturne et contemplez les lumières."
    },
    abilitiesMap: {
      "5% chance when critical hitting to increase Critical Hit by 20% for 10 seconds.": "5% de chance lors d'un coup critique d'augmenter le Coup Critique de 20% pendant 10s.",
      "10% chance when critical hitting to increase Critical Hit by 30% for 10 seconds.": "10% de chance lors d'un coup critique d'augmenter le Coup Critique de 30% pendant 10s.",
      "When taking damage, you have a 10% chance to gain a 20% reflect shield for 10 seconds. Has a 1 minute cooldown.": "En subissant des dégâts, 10% de chance d'obtenir un bouclier réflecteur de 20% pendant 10s (recharge 1m).",
      "When taking damage, you have a 20% chance to gain a 30% reflect shield for 10 seconds. Has a 1 minute cooldown.": "En subissant des dégâts, 20% de chance d'obtenir un bouclier réflecteur de 30% pendant 10s (recharge 1m).",
      "When taking damage, you have a 30% chance to gain a 45% reflect shield and 30% damage reduction for 10 seconds. Has a 1 minute cooldown.": "En subissant des dégâts, 30% de chance d'obtenir un bouclier réflecteur de 45% et 30% de réduction de dégâts pendant 10s.",
      "When dropping below 30% health, gain a 6% Outgoing damage buff and 10% Attack Speed for 10 seconds. 120 second cooldown.": "En passant sous 30% de PV, gagnez 6% de dégâts et 10% de vitesse d'attaque pendant 10s.",
      "When dropping below 40% health, gain a 8% Outgoing damage buff and 10% Attack Speed for 10 seconds. 120 second cooldown.": "En passant sous 40% de PV, gagnez 8% de dégâts et 10% de vitesse d'attaque pendant 10s.",
      "When dropping below 45% health, gain a 10% Outgoing damage buff and 10% Attack Speed for 10 seconds. 120 second cooldown.": "En passant sous 45% de PV, gagnez 10% de dégâts et 10% de vitesse d'attaque pendant 10s.",
      "When dropping below 45% health, gain a 12% Outgoing damage buff and 10% Attack Speed for 15 seconds. 120 second cooldown.": "En passant sous 45% de PV, gagnez 12% de dégâts et 10% de vitesse d'attaque pendant 15s.",
      "Increases amount of ore mined by 10%. ": "Augmente la quantité de minerai extrait de 10%.",
      "Increases amount of ore mined by 15%. ": "Augmente la quantité de minerai extrait de 15%.",
      "Increases experience gain by 5%. ": "Augmente le gain d'expérience de 5%.",
      "Increases harvesting by 10%. ": "Augmente la récolte de 10%.",
      "Increases harvesting by 15%. ": "Augmente la récolte de 15%.",
      "Slightly increases gathering range when mounted. ": "Augmente légèrement la portée de récolte à monture.",
      "Moderately increases gathering range when mounted. ": "Augmente modérément la portée de récolte à monture.",
      "Greatly increases gathering range when mounted.": "Augmente grandement la portée de récolte à monture.",
      "50% chance when using a Flask to gain either a 25% Bonus Damage, 200 Stability, or 200% Bonus Health Regen.": "50% de chance en utilisant une fiole d'obtenir 25% de dégâts, 200 de stabilité ou 200% de régénération de santé.",
      "100% chance when using a Flask to gain either a 25% Bonus Damage, 200 Stability, or 200% Bonus Health Regen.": "100% de chance en utilisant une fiole d'obtenir 25% de dégâts, 200 de stabilité ou 200% de régénération de santé.",
      "10% chance to gain a random emblem effect when using a flask.": "10% de chance d'obtenir un effet d'emblème aléatoire en utilisant une fiole.",
      "5% chance to gain a flask charge when using a Flask.": "5% de chance de récupérer une charge de fiole en l'utilisant.",
      "10% chance to gain a flask charge when using a Flask.": "10% de chance de récupérer une charge de fiole en l'utilisant.",
      "Damaging enemies grants 10% Life Leech.": "Infliger des dégâts aux ennemis octroie 10% de vol de vie.",
      "Damaging enemies grants 20% Life Leech. ": "Infliger des dégâts aux ennemis octroie 20% de vol de vie.",
      "After defeating a Sundered Uplands 5 Star Boss, gain 10% increased Physical and Magic Damage for 4 hours.": "Après avoir vaincu un Boss 5 Étoiles des Sundered Uplands, gagnez 10% de dégâts pendant 4h.",
      "After defeating a Sundered Uplands 5 Star Boss, gain 15% increased Physical and Magic Damage for 4 hours.": "Après avoir vaincu un Boss 5 Étoiles des Sundered Uplands, gagnez 15% de dégâts pendant 4h.",
      "After defeating a delve boss, gain 20% damage reduction for 30 minutes. ": "Après avoir vaincu un boss de delve, gagnez 20% de réduction de dégâts pendant 30m.",
      "Increases the Depths boon damage reduction to 25% and duration to 1 hour.": "Augmente la réduction de dégâts du bonus des profondeurs à 25% et la durée à 1h."
    },
    obtainablesMap: {
      "Grants a Balefire Dragon Egg Fragment when unlocked.": "Confère un fragment d'œuf de dragon Balefire lors du déverrouillage.",
      "Grants a Caprian Dragon Egg Fragment when upgrading.": "Confère un fragment d'œuf de dragon Caprian lors de l'amélioration.",
      "Grants a Caprian Dragon Egg Fragment when upgrading": "Confère un fragment d'œuf de dragon Caprian lors de l'amélioration",
      "Grants Ursa Minor when upgrading": "Confère Ursa Minor lors de l'amélioration",
      "Grants Ursa Major when upgrading": "Confère Ursa Major lors de l'amélioration",
      "Grants Staruable when upgrading": "Confère Staruable lors de l'amélioration",
      "Grants Star Dust when upgrading": "Confère de la Poussière d'Étoile lors de l'amélioration",
      "Grants Star Sebastian when upgrading": "Confère Star Sebastian lors de l'amélioration",
      "Grants Charter's Chair when upgrading": "Confère la Chaise de Charte lors de l'amélioration",
      "Grants Starry Skyfire when upgrading": "Confère Starry Skyfire lors de l'amélioration",
      "Grants Scorpius when upgrading": "Confère Scorpius lors de l'amélioration"
    }
  },
  es: {
    constellationCombat: 'Constelación del Combate',
    constellationGathering: 'Constelación de la Recolección',
    constellationCubesly: 'Constelación de Cubesly',
    recommendedBuilds: 'Builds Recomendadas ▾',
    clearAll: 'Borrar Todo',
    full: 'Lleno',
    buildSummary: 'Resumen de la Build',
    copyBuildCode: 'Copiar Código',
    copied: '✓ Copiado',
    pastePlaceholder: 'Pega el código de la build...',
    load: 'Cargar',
    nodes: 'Nodos',
    stats: 'Estadísticas',
    abilities: 'Habilidades',
    obtainables: 'Obtenibles',
    noStats: 'Sin estadísticas seleccionadas.',
    noAbilities: 'Sin habilidades seleccionadas.',
    noObtainables: 'Sin obtenibles seleccionados.',
    upgrades: 'Mejoras:',
    titleDesc: '✦ \u00A0Simulador de Mapa Estelar',
    introText: 'Tres constelaciones de estrellas te esperan. Haz clic en cualquier nodo para seleccionarlo. Haz doble clic en un diamante raíz para seleccionar toda la constelación. Puedes desbloquear hasta 40 nodos por build.',
    credits: 'Créditos: BetterTroveTools · AallynReed',
    loreKeyTitle: 'Llave de Constelación',
    loreKeyDesc: 'Desbloquea o reinicia ramas. Las primeras 3: 250 Flux en El Celestial.',
    loreSphereTitle: 'Esfera Celestial',
    loreSphereDesc: 'Desbloquea un nodo específico. Solo 40 Esferas disponibles para 120 ranuras.',
    loreEchoesTitle: 'Ecos Astrales',
    loreEchoesDesc: 'Moneda para Esferas. Se obtiene en mazmorras/delves, tomo semanal y vendedores.',
    builds: {
      physLight: 'Daño Físico / Luz',
      magicLight: 'Daño Mágico / Luz',
      magicSpeedLight: 'Daño Mágico / Velocidad de Movimiento / Luz',
      physSpeedLight: 'Daño Físico / Velocidad de Movimiento / Luz'
    },
    statNames: {
      "Physical Damage": "Daño Físico",
      "Magic Damage": "Daño Mágico",
      "Critical Hit": "Golpe Crítico",
      "Critical Damage": "Daño Crítico",
      "Attack Speed": "Velocidad de Ataque",
      "Movement Speed": "Velocidad de Movimiento",
      "Maximum Health %": "Salud Máxima %",
      "Health Regen": "Regeneración de Salud",
      "Energy Regen": "Regeneración de Energía",
      "Damage Reduction": "Reducción de Daño",
      "Incoming Damage": "Daño Recibido",
      "Outgoing Damage": "Daño Infligido",
      "Flask Capacity": "Capacidad de Viales",
      "Magic Find": "Hallazgo Mágico",
      "Lasermancy": "Lasermancia",
      "Experience Gain": "Ganancia de Experiencia",
      "Crafting Speed": "Velocidad de Creación",
      "Jump": "Salto",
      "Stability": "Estabilidad",
      "Light": "Luz",
      "Random Flask Emblem": "Emblema de Vial Aleatorio"
    },
    nodeNames: {
      "Strength": "Fuerza",
      "Lucky Strikes": "Golpes Afortunados",
      "Haste": "Celeridad",
      "Accuracy": "Precisión",
      "Leaping and Anti-Knockback": "Salto y Anti-Empuje",
      "Lucky Strikes 2.0": "Golpes Afortunados 2.0",
      "Accuracy, Intellect and Strength": "Precisión, Intelecto y Fuerza",
      "Accuracy and Heartiness": "Precisión y Vigor",
      "Reflection": "Reflejo",
      "Reflection 2.0": "Reflejo 2.0",
      "Protection": "Protección",
      "Reflection 3.0": "Reflejo 3.0",
      "Anti-Knockback": "Anti-Empuje",
      "Intellect": "Intelecto",
      "Rage": "Furia",
      "Heartiness": "Vigor",
      "Rage 1.5": "Furia 1.5",
      "Speed": "Velocidad",
      "Rage 2.5": "Furia 2.5",
      "Rage 3.0": "Furia 3.0",
      "Weakness": "Debilidad",
      "Critical": "Crítico",
      "Weakness 1.5": "Debilidad 1.5",
      "Luck": "Suerte",
      "Shard Searcher": "Buscador de Fragmentos",
      "Mining": "Minería",
      "Knowledge": "Conocimiento",
      "Knowledge and Luck": "Conocimiento y Suerte",
      "Knowledge and Accuracy": "Conocimiento y Precisión",
      "Knowledge and Critical": "Conocimiento y Crítico",
      "Luck and DYI": "Suerte y Bricolaje",
      "Alchemy, Heartiness and Leaping": "Alquimia, Vigor y Salto",
      "Harvest": "Cosecha",
      "Heartiness and Healing": "Vigor y Curación",
      "Harvest 2.0": "Cosecha 2.0",
      "Haste and Critical": "Celeridad y Crítico",
      "Attack": "Ataque",
      "Shard Searcher 2.0": "Buscador de Fragmentos 2.0",
      "Mining and Heartiness": "Minería y Vigor",
      "Alchemy": "Alquimia",
      "Healing and Caffeine": "Curación y Cafeína",
      "Mining and Leaps": "Minería y Saltos",
      "Long Reach": "Alcance Largo",
      "Alchemy and Healing": "Alquimia y Curación",
      "Sundard Flight": "Vuelo Cereal",
      "Sundered Flight 2.0": "Vuelo Cereal 2.0",
      "Sundered Flight 3.0": "Vuelo Cereal 3.0",
      "Long Reach 2.0": "Alcance Largo 2.0",
      "Long Reach 3.0": "Alcance Largo 3.0",
      "Heartiness, Haste and Mining": "Vigor, Celeridad y Minería",
      "Minor Buffing": "Mejora Menor",
      "Accuracy and Critical": "Precisión y Crítico",
      "Greater Alchemic Power": "Gran Poder Alquímico",
      "Greater Alchemic Power 2.0": "Gran Poder Alquímico 2.0",
      "Greater Alchemic Power 3.0": "Gran Poder Alquímico 3.0",
      "Flask Renewal": "Renovación de Vial",
      "Flask Renewal 2.0": "Renovación de Vial 2.0",
      "Minor Buffing Always": "Mejora Menor Permanente",
      "Strength and Intellect": "Fuerza e Intelecto",
      "Healing": "Curación",
      "Draining Kiss": "Beso Drenante",
      "Healing and Heartiness": "Curación y Vigor",
      "Bounty Hunt Boon": "Bono de Caza",
      "Bounty Hunt": "Caza de Recompensas",
      "Light": "Luz",
      "Depths Boon": "Bono de Profundidades",
      "Depths Boon 2.0": "Bono de Profundidades 2.0"
    },
    descriptions: {
      "Within the Strength side of the constellation we try to make Physical based classes tougher than the squishy magic ones.": "En el lado de Fuerza de la constelación intentamos hacer más resistentes a las clases físicas.",
      "Slot machine of extra damage. I like it.": "Máquina tragamonedas de daño extra. Me gusta.",
      "Hitting more often means more Critical Hits.": "Golpear más a menudo significa más Golpes Críticos.",
      "A star viewing will lead you to never missing your target's weakness.": "Observar esta estrella te guiará para no fallar la debilidad del objetivo.",
      "If you get knocked back, you cannot critically hit as much.": "Si te empujan hacia atrás, no puedes asestar tantos golpes críticos.",
      "Look to the stars for a class that can use lots of critical hit...It's not up there.": "Busca en las estrellas una clase experta en críticos... No está ahí arriba.",
      "More Strikes then equals less pins to hit.": "Más golpes equivalen a menos objetivos que derribar.",
      "Wow... Magic and Physical Damage with a little Critical Hit... Maybe this should be a Major Star.": "Daño mágico y físico con golpe crítico... ¡Debería ser una estrella mayor!",
      "Finding this star could grant more then just Health and Critical Hit.": "Encontrar esta estrella otorga más que solo salud y golpe crítico.",
      "Accurately read the stars.": "Lee atentamente las estrellas.",
      "They hit you and you hit them back.": "Te golpean y tú respondes al golpe.",
      "Continue to grow your strength and prove Might is better then brains.": "Demuestra que la fuerza bruta supera al intelecto.",
      "Reflect even more damage back at your foes.": "Refleja aún más daño de vuelta a tus enemigos.",
      "Attack and defend is what these stars are about.": "Ataque y defensa son la clave de estas estrellas.",
      "YESSSS... MORE STRENGTH!!!!": "¡SÍ! ¡MÁS FUERZA!",
      "Additional shields will be needed for future bosses.": "Se necesitarán escudos adicionales para los futuros jefes.",
      "Will need to double check numbers to make sure this is not too much strength.": "Verifiquemos que esta fuerza no sea excesiva.",
      "This star should help balance melee a little more.": "Esta estrella ayuda a equilibrar el combate cuerpo a cuerpo.",
      "Ultimate Strength star is better than a Magic Star.": "La estrella de fuerza definitiva supera a una estrella mágica.",
      "Not going to push around the brawler.": "Nadie va a empujar a este luchador.",
      "Gain greater arcane knowledge to blast your foe down this path.": "Obtén un conocimiento arcano superior para aniquilar enemigos.",
      "Star of ARRRRRRRRRRRRRRR!!!!!": "¡Estrella del rugido de furia!",
      "This star come with a free library card. Somehow that's what increases your damage.": "¡Esta estrella incluye una tarjeta de biblioteca gratis!",
      "Look at this star trying to make you less squishy over here.": "Una estrella dedicada a hacerte más resistente.",
      "Wow, mind exploded.": "Un conocimiento asombroso.",
      "This star's blessing hopes you live a long and healthy life.": "La bendición de esta estrella te desea una larga vida.",
      "Give in to your anger.": "Cede ante tu ira.",
      "Even though most magic classes have good range, here is some stability so you don't go flying.": "Estabilidad para evitar salir volando por los golpes.",
      "Little bit of speed for slow magic classes.": "Un poco de velocidad para clases mágicas lentas.",
      "Unlimited Magic... unless you run out of energy regen.": "Magia ilimitada... mientras regeneres energía.",
      "Oops, didn't I mean to make this a health star?": "¿No se suponía que esta era una estrella de salud?",
      "Kind of odd that the intellect tree has a rage mechanic...I guess it's a nerd rage.": "Una mecánica de furia en la rama de intelecto... ¡Ira de sabio!",
      "Ahhh this is where I put that Health Star.": "¡Ah! Aquí es donde estaba esa estrella de salud.",
      "The final star spell is ready. Are you ready to cast it?": "El hechizo final está listo. ¿Estás listo para lanzarlo?",
      "This Star represents our home which was destroyed by the Void.": "Esta estrella representa nuestro hogar destruido por el Vacío.",
      "You have found the Weakness, now keep on attacking.": "Has encontrado la debilidad, sigue atacando.",
      "Stop being so critical.": "¡No seas tan crítico!",
      "A star all about seeing overly sized numbers appearing.": "Una estrella para ver aparecer números de daño gigantes.",
      "A Critical Hit!": "¡Un Golpe Crítico!",
      "Search the lands for greater goods.": "Explora las tierras en busca de grandes bienes.",
      "Guides you to finding even more useful ore.": "Te guía para encontrar minerales aún más útiles.",
      "Show how to have more mastery over your laser.": "Demuestra un mayor dominio de tu láser.",
      "Knowledge is power - with this you will gain even more.": "El conocimiento es poder: aprende aún más.",
      "With a little luck and brains you can do anything.": "Con suerte y cerebro, todo es posible.",
      "See the weakness of your enemies and know how to exploit it.": "Observa la debilidad enemiga y aprovéchala.",
      "A star too small to be a planet but hurts too much to accept the truth.": "Una estrella diminuta pero increíblemente poderosa.",
      "So glad to see you all the way out here, the star focuses on finding better gear.": "Qué bueno verte por aquí: esta estrella ayuda a hallar mejor equipo.",
      "Speeds up crafting...I know I would love that.": "Acelera la creación de objetos.",
      "Leap for the stars!!!!": "¡Salta hacia las estrellas!",
      "Grow even more crops.": "Cultiva aún más cosecha.",
      "Grants the feeling of vigor you get from eating a large meal.": "La sensación de vigor tras un gran banquete.",
      "Ultimate Harvest upgrade for any gathering min/maxer.": "La mejora de cosecha definitiva para optimizadores.",
      "A reward for gathering - hitting hard and fast.": "Recompensa de recolección: golpear fuerte y rápido.",
      "When searching for items, you have gained greater defense.": "Al buscar objetos, tu defensa aumenta.",
      "Working on mining has given you a little more edge.": "El trabajo minero te da ventaja en combate.",
      "Lots more shiny ore to collect.": "Muchos más minerales brillantes por recolectar.",
      "This is the end of the path... was it worth it?": "Es el final del camino... ¿Valió la pena?",
      "An extra flask here and there, soon you'll be invincible...": "Un vial extra por aquí y por allá para ser invencible...",
      "A little bit of coffee will heal anyone.": "Un buen café cura a cualquiera.",
      "Mine with ease of being able to jump a little more.": "Mina fácilmente mientras saltas un poco más.",
      "When mounted, Harvest at short range.": "En montura, cosecha a corto alcance.",
      "Gain healing and the ability to heal more. Sounds good, right?": "Cúrate y aumenta tu capacidad de curación.",
      "Fly free you fools in the Sundered Uplands.": "Vuela libremente en Sundered Uplands.",
      "Fly even faster.": "Vuela aún más rápido.",
      "I am like a dragon, I only fly away.": "Como un dragón, solo me elevo en el aire.",
      "This star gains the boon of health and mining.": "Esta estrella otorga salud y habilidades mineras.",
      "When mounted, Harvest at medium range.": "En montura, cosecha a alcance medio.",
      "After searching the stars, you have gained increased magic.": "Al buscar en las estrellas, tu magia aumenta.",
      "Hee Hee this star gives more health.": "¡Ji, ji! Esta estrella otorga más salud.",
      "When mounted Harvest at Loooooooooooonger range. \nGrants a Balefire Dragon Egg Fragment when unlocked.": "En montura, cosecha a larguísimo alcance.",
      "Exploring and armoring up.": "Explora y refuerza tu armadura.",
      "Seeing the final frontier has left you tough.": "Ver la frontera final te ha hecho endurecerte.",
      "Intense searching has led you to greater speed and adaptability.": "Tu búsqueda te aporta velocidad y adaptabilidad.",
      "Extra flasks are always good.": "Viales extra siempre son bienvenidos.",
      "Magic power from gathering so much knowledge.": "Poder mágico acumulado por el conocimiento.",
      "You did so much Mining it improved your Physical Damage. Noice.": "¡Tanto minar mejoró tu daño físico!",
      "Increased experience gain is always good.": "Mayor ganancia de experiencia siempre viene bien.",
      "Little bit of luck on this side of the stars as well.": "Un poco de suerte extra de este lado de las estrellas.",
      "Gathering stars together has increased your strength.": "Reunir las estrellas ha aumentado tu fuerza.",
      "A branch of a constellation related to Flasks? What could go wrong?": "¿Una rama ligada a viales? ¿Qué podría salir mal?",
      "Random buffs are always great because they are buffs.": "Mejoras aleatorias siguen siendo excelentes mejoras.",
      "Real Critting is more about following your heart than following a build.": "Asestar críticos reales es seguir tu corazón.",
      "This should help you jump and not get thrown across the room in delves.": "Ayuda a saltar sin salir volando en las delves.",
      "Why are flasks so OP... here is a random one.": "¿Por qué los viales son tan poderosos?",
      "More random effects. MOOOOORREEEEE!!!!": "¡Aún más efectos aleatorios!",
      "A higher chance to get additional effects is always good.": "Mayor probabilidad de efectos adicionales.",
      "This shooting star is so fast it teaches trovians to hit faster.": "Una estrella fugaz que enseña a golpear más rápido.",
      "Little bit of speed to help you in the world.": "Un poco de velocidad para explorar el mundo.",
      "Fighting throughout this Trovian world has given you the intellect to randomly recharge flasks.": "Luchar te permite recargar viales aleatoriamente.",
      "When visiting the final frontier, it's always good to have speed.": "La velocidad es clave para explorar la frontera final.",
      "Star of health bless us with more health please.": "¡Estrella de la salud, concédenos más vida!",
      "Attack speed is all some classes need.": "La velocidad de ataque es todo lo que algunas clases necesitan.",
      "A Blessing of bountiful flasks... I really hope this is not too OP... Maybe I need to nerf Death-Defying...": "Bendición de viales abundantes...",
      "Now that flasks are powered up, heres a few more.": "Ahora que los viales son poderosos, aquí hay más.",
      "So Many Flasks!!!!!": "¡Tantos viales!",
      "You get a buff and you get a buff, everybody gets a buff.": "¡Mejoras para todo el mundo!",
      "Drinking too many flasks has made the random buffs gained from them stick.": "Consumir viales prolonga sus efectos.",
      "The shield may be just as important as DPS number charts.": "El escudo es tan crucial como tus listas de daño.",
      "Moooooooooooreeeeeeeee Healing PLEASE!!!": "¡Más curación, por favor!",
      "Star of speed give me swiftness to strike my foes.": "Estrella de la velocidad, dame rapidez.",
      "Drain health from your enemies.": "Drena la salud de tus enemigos.",
      "Attacks so fast you can not even animate fast enough.": "¡Ataques tan rápidos que ni se pueden animar!",
      "In this constellation of dungeon seeking we greet thee with more health.": "En esta constelación te otorgamos más salud.",
      "With faster attack and higher life leech you may someday be invincible.": "Ataques rápidos y robo de vida te hacen invencible.",
      "Two damage types, maybe someday we will search the stars and find the 3rd one.": "Dos tipos de daño hoy, ¿un tercero pronto?",
      "Speed through the stars for greater power.": "Recorre las estrellas para más poder.",
      "One day it will be super important to have a lot of this. Wink Wink": "¡Un día esta estadística será súper importante!",
      "Fly, you fools, Fly to the end of that Delve.": "¡Vuelen hasta el fondo de esa Delve!",
      "Hunting enemies now grants you boons.": "Cazar enemigos te otorga bendiciones.",
      "Looking up at the stars has granted additional buff time.": "Observar las estrellas prolonga tus mejoras.",
      "Grant me the true power of the stars. May I destroy the darkness of the cosmos.": "Concédeme el verdadero poder celestial.",
      "Wink Wink...": "Guiño, guiño...",
      "Jump up without being pushed around by bullies.": "Salta sin que te empujen los enemigos.",
      "Looking to the stars to decide how to increase those damage numbers.": "Consulta las estrellas para aumentar tu daño.",
      "Greater shining light to destroy the dark.": "Una luz brillante para destruir la oscuridad.",
      "Oops, did I leave a flask over on this side of the cosmos.": "Ups, ¿olvidé un vial de este lado?",
      "Delving just got a little bit easier.": "Explorar las Delves es un poco más fácil.",
      "A little more time to the boon you just got.": "Extiende la duración de la mejora obtenida.",
      "Look up at the sky one night and see the lights above.": "Mira al cielo nocturno y contempla las luces."
    },
    abilitiesMap: {
      "5% chance when critical hitting to increase Critical Hit by 20% for 10 seconds.": "5% de probabilidad al asestar un golpe crítico de aumentar Golpe Crítico en 20% durante 10s.",
      "10% chance when critical hitting to increase Critical Hit by 30% for 10 seconds.": "10% de probabilidad al asestar un golpe crítico de aumentar Golpe Crítico en 30% durante 10s.",
      "When taking damage, you have a 10% chance to gain a 20% reflect shield for 10 seconds. Has a 1 minute cooldown.": "Al recibir daño, tienes un 10% de probabilidad de obtener un escudo reflejante del 20% durante 10s.",
      "When taking damage, you have a 20% chance to gain a 30% reflect shield for 10 seconds. Has a 1 minute cooldown.": "Al recibir daño, tienes un 20% de probabilidad de obtener un escudo reflejante del 30% durante 10s.",
      "When taking damage, you have a 30% chance to gain a 45% reflect shield and 30% damage reduction for 10 seconds. Has a 1 minute cooldown.": "Al recibir daño, tienes un 30% de probabilidad de obtener un escudo reflejante del 45% y 30% de reducción de daño durante 10s.",
      "When dropping below 30% health, gain a 6% Outgoing damage buff and 10% Attack Speed for 10 seconds. 120 second cooldown.": "Al caer por debajo del 30% de salud, obtienes un 6% de daño infligido y 10% de velocidad de ataque durante 10s.",
      "When dropping below 40% health, gain a 8% Outgoing damage buff and 10% Attack Speed for 10 seconds. 120 second cooldown.": "Al caer por debajo del 40% de salud, obtienes un 8% de daño infligido y 10% de velocidad de ataque durante 10s.",
      "When dropping below 45% health, gain a 10% Outgoing damage buff and 10% Attack Speed for 10 seconds. 120 second cooldown.": "Al caer por debajo del 45% de salud, obtienes un 10% de daño infligido y 10% de velocidad de ataque durante 10s.",
      "When dropping below 45% health, gain a 12% Outgoing damage buff and 10% Attack Speed for 15 seconds. 120 second cooldown.": "Al caer por debajo del 45% de salud, obtienes un 12% de daño infligido y 10% de velocidad de ataque durante 15s.",
      "Increases amount of ore mined by 10%. ": "Aumenta la cantidad de mineral minado en un 10%.",
      "Increases amount of ore mined by 15%. ": "Aumenta la cantidad de mineral minado en un 15%.",
      "Increases experience gain by 5%. ": "Aumenta la ganancia de experiencia en un 5%.",
      "Increases harvesting by 10%. ": "Aumenta la cosecha en un 10%.",
      "Increases harvesting by 15%. ": "Aumenta la cosecha en un 15%.",
      "Slightly increases gathering range when mounted. ": "Aumenta ligeramente el alcance de recolección en montura.",
      "Moderately increases gathering range when mounted. ": "Aumenta moderadamente el alcance de recolección en montura.",
      "Greatly increases gathering range when mounted.": "Aumenta enormemente el alcance de recolección en montura.",
      "50% chance when using a Flask to gain either a 25% Bonus Damage, 200 Stability, or 200% Bonus Health Regen.": "50% de probabilidad al usar un vial de obtener un 25% de daño bonus, 200 de estabilidad o 200% de regeneración de salud.",
      "100% chance when using a Flask to gain either a 25% Bonus Damage, 200 Stability, or 200% Bonus Health Regen.": "100% de probabilidad al usar un vial de obtener un 25% de daño bonus, 200 de estabilidad o 200% de regeneración de salud.",
      "10% chance to gain a random emblem effect when using a flask.": "10% de probabilidad de obtener un efecto de emblema aleatorio al usar un vial.",
      "5% chance to gain a flask charge when using a Flask.": "5% de probabilidad de ganar una carga de vial al usar un vial.",
      "10% chance to gain a flask charge when using a Flask.": "10% de probabilidad de ganar una carga de vial al usar un vial.",
      "Damaging enemies grants 10% Life Leech.": "Infligir daño a los enemigos otorga un 10% de robo de vida.",
      "Damaging enemies grants 20% Life Leech. ": "Infligir daño a los enemigos otorga un 20% de robo de vida.",
      "After defeating a Sundered Uplands 5 Star Boss, gain 10% increased Physical and Magic Damage for 4 hours.": "Tras derrotar a un Boss de 5 Estrellas de Sundered Uplands, obtienes 10% más de daño durante 4h.",
      "After defeating a Sundered Uplands 5 Star Boss, gain 15% increased Physical and Magic Damage for 4 hours.": "Tras derrotar a un Boss de 5 Estrellas de Sundered Uplands, obtienes 15% más de daño durante 4h.",
      "After defeating a delve boss, gain 20% damage reduction for 30 minutes. ": "Tras derrotar a un boss de delve, obtienes un 20% de reducción de daño durante 30m.",
      "Increases the Depths boon damage reduction to 25% and duration to 1 hour.": "Aumenta la reducción de daño del bono de profundidades al 25% y la duración a 1h."
    },
    obtainablesMap: {
      "Grants a Balefire Dragon Egg Fragment when unlocked.": "Otorga un fragmento de huevo de dragón Balefire al desbloquear.",
      "Grants a Caprian Dragon Egg Fragment when upgrading.": "Otorga un fragmento de huevo de dragón Caprian al mejorar.",
      "Grants a Caprian Dragon Egg Fragment when upgrading": "Otorga un fragmento de huevo de dragón Caprian al mejorar",
      "Grants Ursa Minor when upgrading": "Otorga Ursa Minor al mejorar",
      "Grants Ursa Major when upgrading": "Otorga Ursa Major al mejorar",
      "Grants Staruable when upgrading": "Otorga Staruable al mejorar",
      "Grants Star Dust when upgrading": "Otorga Polvo Estelar al mejorar",
      "Grants Star Sebastian when upgrading": "Otorga Star Sebastian al mejorar",
      "Grants Charter's Chair when upgrading": "Otorga la Silla de Carta al mejorar",
      "Grants Starry Skyfire when upgrading": "Otorga Starry Skyfire al mejorar",
      "Grants Scorpius when upgrading": "Otorga Scorpius al mejorar"
    }
  },
  zh: {
    constellationCombat: '战斗星座',
    constellationGathering: '采集星座',
    constellationCubesly: '魔方星云',
    recommendedBuilds: '推荐构筑 ▾',
    clearAll: '清空全选',
    full: '已满',
    buildSummary: '构筑汇总',
    copyBuildCode: '复制构筑代码',
    copied: '✓ 已复制',
    pastePlaceholder: '在此粘贴构筑代码...',
    load: '加载',
    nodes: '星号节点',
    stats: '属性总和',
    abilities: '技能效果',
    obtainables: '可获取物品',
    noStats: '未选择任何属性节点。',
    noAbilities: '未选择任何技能节点。',
    noObtainables: '未选择任何物品节点。',
    upgrades: '提升节点：',
    titleDesc: '✦ \u00A0星图模拟器',
    introText: '三大星座等待你的探索。点击任意节点即可解锁，前置节点将自动选中。双击核心根节点可解锁整个分支。每套构筑最多解锁 40 个节点。',
    credits: '致谢：BetterTroveTools · AallynReed',
    loreKeyTitle: '星座钥匙',
    loreKeyDesc: '用于解锁或重置分支。前 3 把在天界处消耗 250 原石购买。',
    loreSphereTitle: '天界球',
    loreSphereDesc: '解锁特定节点。120 个槽位中仅可解锁 40 个，请谨慎规划。',
    loreEchoesTitle: '星界回响',
    loreEchoesDesc: '兑换天界球的货币。可在副本/地窖 (20-50/次)、每周圣典 (5000/周) 及商店处获取。',
    builds: {
      physLight: '物理伤害 / 光芒值',
      magicLight: '魔法伤害 / 光芒值',
      magicSpeedLight: '魔法伤害 / 移动速度 / 光芒值',
      physSpeedLight: '物理伤害 / 移动速度 / 光芒值'
    },
    statNames: {
      "Physical Damage": "物理伤害",
      "Magic Damage": "魔法伤害",
      "Critical Hit": "暴击率",
      "Critical Damage": "暴击伤害",
      "Attack Speed": "攻击速度",
      "Movement Speed": "移动速度",
      "Maximum Health %": "最大生命值 %",
      "Health Regen": "生命回复",
      "Energy Regen": "能量回复",
      "Damage Reduction": "伤害减免",
      "Incoming Damage": "承受伤害",
      "Outgoing Damage": "造成伤害",
      "Flask Capacity": "药水容量",
      "Magic Find": "寻宝值",
      "Lasermancy": "激光术",
      "Experience Gain": "经验获取",
      "Crafting Speed": "制作速度",
      "Jump": "跳跃",
      "Stability": "稳定性",
      "Light": "光芒值",
      "Random Flask Emblem": "随机药水徽章"
    },
    nodeNames: {
      "Strength": "力量",
      "Lucky Strikes": "幸运连击",
      "Haste": "急速",
      "Accuracy": "精准",
      "Leaping and Anti-Knockback": "跳跃与抗击退",
      "Lucky Strikes 2.0": "幸运连击 2.0",
      "Accuracy, Intellect and Strength": "精准、智力与力量",
      "Accuracy and Heartiness": "精准与体魄",
      "Reflection": "伤害反射",
      "Reflection 2.0": "伤害反射 2.0",
      "Protection": "防护",
      "Reflection 3.0": "伤害反射 3.0",
      "Anti-Knockback": "抗击退",
      "Intellect": "智力",
      "Rage": "狂暴",
      "Heartiness": "体魄",
      "Rage 1.5": "狂暴 1.5",
      "Speed": "速度",
      "Rage 2.5": "狂暴 2.5",
      "Rage 3.0": "狂暴 3.0",
      "Weakness": "弱点打击",
      "Critical": "暴击",
      "Weakness 1.5": "弱点打击 1.5",
      "Luck": "幸运",
      "Shard Searcher": "晶石寻宝者",
      "Mining": "采矿",
      "Knowledge": "知识",
      "Knowledge and Luck": "知识与幸运",
      "Knowledge and Accuracy": "知识与精准",
      "Knowledge and Critical": "知识与暴击",
      "Luck and DYI": "幸运与手工",
      "Alchemy, Heartiness and Leaping": "炼金、体魄与跳跃",
      "Harvest": "丰收",
      "Heartiness and Healing": "体魄与自愈",
      "Harvest 2.0": "丰收 2.0",
      "Haste and Critical": "急速与暴击",
      "Attack": "攻击",
      "Shard Searcher 2.0": "晶石寻宝者 2.0",
      "Mining and Heartiness": "采矿与体魄",
      "Alchemy": "炼金术",
      "Healing and Caffeine": "自愈与提神",
      "Mining and Leaps": "采矿与跳跃",
      "Long Reach": "远距离采集",
      "Alchemy and Healing": "炼金与自愈",
      "Sundard Flight": "断裂之空飞行",
      "Sundered Flight 2.0": "断裂之空飞行 2.0",
      "Sundered Flight 3.0": "断裂之空飞行 3.0",
      "Long Reach 2.0": "远距离采集 2.0",
      "Long Reach 3.0": "远距离采集 3.0",
      "Heartiness, Haste and Mining": "体魄、急速与采矿",
      "Minor Buffing": "初级增益",
      "Accuracy and Critical": "精准与暴击",
      "Greater Alchemic Power": "高等炼金之力",
      "Greater Alchemic Power 2.0": "高等炼金之力 2.0",
      "Greater Alchemic Power 3.0": "高等炼金之力 3.0",
      "Flask Renewal": "药水充能",
      "Flask Renewal 2.0": "药水充能 2.0",
      "Minor Buffing Always": "常驻初级增益",
      "Strength and Intellect": "力量与智力",
      "Healing": "自愈",
      "Draining Kiss": "吸血之吻",
      "Healing and Heartiness": "自愈与体魄",
      "Bounty Hunt Boon": "赏金狩猎加成",
      "Bounty Hunt": "赏金狩猎",
      "Light": "光芒值",
      "Depths Boon": "地窖庇护",
      "Depths Boon 2.0": "地窖庇护 2.0"
    },
    descriptions: {
      "Within the Strength side of the constellation we try to make Physical based classes tougher than the squishy magic ones.": "在力量星系侧，我们致力于让物理系职业比脆弱的魔法职业更加坚韧。",
      "Slot machine of extra damage. I like it.": "额外伤害老虎机。我喜欢！",
      "Hitting more often means more Critical Hits.": "攻击频率更高意味着造成更多暴击。",
      "A star viewing will lead you to never missing your target's weakness.": "观星将引导你精准锁定敌人的弱点。",
      "If you get knocked back, you cannot critically hit as much.": "如果被击退，你将无法频繁造成暴击。",
      "Look to the stars for a class that can use lots of critical hit...It's not up there.": "寻找擅长暴击的职业... 它并不在此处。",
      "More Strikes then equals less pins to hit.": "击打次数越多，剩余目标就越少。",
      "Wow... Magic and Physical Damage with a little Critical Hit... Maybe this should be a Major Star.": "魔法与物理伤害附带暴击... 也许这该是个主星！",
      "Finding this star could grant more then just Health and Critical Hit.": "寻找此星能获得的远不止生命值与暴击。",
      "Accurately read the stars.": "仔细解读星辰的寓意。",
      "They hit you and you hit them back.": "他们击打你，你便反击回去。",
      "Continue to grow your strength and prove Might is better then brains.": "继续提升力量，证明蛮力胜过头脑。",
      "Reflect even more damage back at your foes.": "向敌人反射更多伤害。",
      "Attack and defend is what these stars are about.": "进攻与防守是这些星辰的核心。",
      "YESSSS... MORE STRENGTH!!!!": "是的！更多力量！！",
      "Additional shields will be needed for future bosses.": "面对未来的 Boss 需要额外的护盾。",
      "Will need to double check numbers to make sure this is not too much strength.": "需要复核数据以确保力量不会过于膨胀。",
      "This star should help balance melee a little more.": "此星有助于进一步平衡近战职业。",
      "Ultimate Strength star is better than a Magic Star.": "极限力量之星胜过魔法之星。",
      "Not going to push around the brawler.": "没人能随心所欲地推倒格斗家。",
      "Gain greater arcane knowledge to blast your foe down this path.": "获得更深奥的术法知识以轰碎前方的敌人。",
      "Star of ARRRRRRRRRRRRRRR!!!!!": "怒吼狂暴之星！",
      "This star come with a free library card. Somehow that's what increases your damage.": "此星附赠免费借书卡，不知为何提升了你的伤害。",
      "Look at this star trying to make you less squishy over here.": "这颗星正努力让你不再脆弱。",
      "Wow, mind exploded.": "思维震撼！",
      "This star's blessing hopes you live a long and healthy life.": "此星的祝福希望你长寿健康。",
      "Give in to your anger.": "顺从你的愤怒。",
      "Even though most magic classes have good range, here is some stability so you don't go flying.": "提供稳定性，避免法系职业在受到重击时飞出。",
      "Little bit of speed for slow magic classes.": "为笨重的法系职业提供少许速度加成。",
      "Unlimited Magic... unless you run out of energy regen.": "无限魔法... 除非你的能量回复中断。",
      "Oops, didn't I mean to make this a health star?": "哎呀，这难道不该是个生命值节点吗？",
      "Kind of odd that the intellect tree has a rage mechanic...I guess it's a nerd rage.": "智力树里有狂暴机制... 大概是学霸的怒火吧。",
      "Ahhh this is where I put that Health Star.": "啊！原来生命值节点在这儿。",
      "The final star spell is ready. Are you ready to cast it?": "终极星辰法术已准备就绪，准备施放了吗？",
      "This Star represents our home which was destroyed by the Void.": "这颗星代表被虚空毁灭的故乡。",
      "You have found the Weakness, now keep on attacking.": "你已发现了弱点，继续猛烈攻击！",
      "Stop being so critical.": "别那么苛刻！",
      "A star all about seeing overly sized numbers appearing.": "专门让你看到超大伤害数值的星辰。",
      "A Critical Hit!": "造成暴击！",
      "Search the lands for greater goods.": "在大陆上搜寻更丰厚的宝物。",
      "Guides you to finding even more useful ore.": "引导你寻找更有用的矿石。",
      "Show how to have more mastery over your laser.": "展示对采矿激光更强的掌控力。",
      "Knowledge is power - with this you will gain even more.": "知识就是力量 — 藉此你将收获更多。",
      "With a little luck and brains you can do anything.": "凭着运气与智慧，你无所不能。",
      "See the weakness of your enemies and know how to exploit it.": "洞察敌人的弱点并善加利用。",
      "A star too small to be a planet but hurts too much to accept the truth.": "小到算不上行星，但威力巨大到难以置信。",
      "So glad to see you all the way out here, the star focuses on finding better gear.": "很高兴你能探索至此，此星专注于寻找更优装备。",
      "Speeds up crafting...I know I would love that.": "加快物品制作速度。",
      "Leap for the stars!!!!": "跃向星空！！",
      "Grow even more crops.": "种植并收获更多作物。",
      "Grants the feeling of vigor you get from eating a large meal.": "体验如同享用美餐后的充沛精力。",
      "Ultimate Harvest upgrade for any gathering min/maxer.": "采集极致追求者的终极收获提升。",
      "A reward for gathering - hitting hard and fast.": "采集的额外回报 — 快速且重棒的打击。",
      "When searching for items, you have gained greater defense.": "在搜寻物品时获得更强的防御。",
      "Working on mining has given you a little more edge.": "长期采矿的锻炼让你在战斗中更具优势。",
      "Lots more shiny ore to collect.": "收集更多闪耀的矿石。",
      "This is the end of the path... was it worth it?": "这是道路的终点... 这值得吗？",
      "An extra flask here and there, soon you'll be invincible...": "到处都有额外的药水，你很快将不可战胜...",
      "A little bit of coffee will heal anyone.": "一杯咖啡能治愈任何人。",
      "Mine with ease of being able to jump a little more.": "在提升跳跃能力的同时轻松采矿。",
      "When mounted, Harvest at short range.": "骑乘状态下近距离采集。",
      "Gain healing and the ability to heal more. Sounds good, right?": "获得治疗能力并大幅提升治疗量。",
      "Fly free you fools in the Sundered Uplands.": "在断裂之空自由翱翔。",
      "Fly even faster.": "飞得更快。",
      "I am like a dragon, I only fly away.": "宛如巨龙般展翅高飞。",
      "This star gains the boon of health and mining.": "获得生命值与采矿的双重庇护。",
      "When mounted, Harvest at medium range.": "骑乘状态下中距离采集。",
      "After searching the stars, you have gained increased magic.": "探索星空后，你的魔力得到了提升。",
      "Hee Hee this star gives more health.": "嘿嘿！这颗星能提供更多生命值。",
      "When mounted Harvest at Loooooooooooonger range. \nGrants a Balefire Dragon Egg Fragment when unlocked.": "骑乘状态下超远距离采集。",
      "Exploring and armoring up.": "在探索中不断强化护甲。",
      "Seeing the final frontier has left you tough.": "领略极限边界后，你变得更加坚韧。",
      "Intense searching has led you to greater speed and adaptability.": "深入搜寻带来了更快的速度与适应能力。",
      "Extra flasks are always good.": "更多的药水总是好的。",
      "Magic power from gathering so much knowledge.": "汲取无尽知识转化为强效魔力。",
      "You did so much Mining it improved your Physical Damage. Noice.": "长期的采矿锻炼提升了你的物理伤害！",
      "Increased experience gain is always good.": "经验加成永远不嫌多。",
      "Little bit of luck on this side of the stars as well.": "星空这一侧同样伴随着好运。",
      "Gathering stars together has increased your strength.": "凝聚星辰之力大幅提升了力量。",
      "A branch of a constellation related to Flasks? What could go wrong?": "与药水相关的分支？能出什么差错呢？",
      "Random buffs are always great because they are buffs.": "随机增益非常实用。",
      "Real Critting is more about following your heart than following a build.": "打出暴击全凭心意，无需刻意追求。",
      "This should help you jump and not get thrown across the room in delves.": "帮助你在地窖中灵活跳跃且不被击飞。",
      "Why are flasks so OP... here is a random one.": "为什么药水如此强力？",
      "More random effects. MOOOOORREEEEE!!!!": "获得更多随机效果！",
      "A higher chance to get additional effects is always good.": "更高概率触发额外效果。",
      "This shooting star is so fast it teaches trovians to hit faster.": "划过天际的流星教会你更快地出招。",
      "Little bit of speed to help you in the world.": "少许速度提升助你探索世界。",
      "Fighting throughout this Trovian world has given you the intellect to randomly recharge flasks.": "丰富的实战经验让你学会随机补充药水。",
      "When visiting the final frontier, it's always good to have speed.": "探索终极边界时，速度至关重要。",
      "Star of health bless us with more health please.": "生命之星，赐予我们更多生命值吧！",
      "Attack speed is all some classes need.": "攻击速度是部分职业的核心需求。",
      "A Blessing of bountiful flasks... I really hope this is not too OP... Maybe I need to nerf Death-Defying...": "丰沛药水的祝福...",
      "Now that flasks are powered up, heres a few more.": "药水强化完成，再来几瓶！",
      "So Many Flasks!!!!!": "药水数量太惊人了！",
      "You get a buff and you get a buff, everybody gets a buff.": "每个人都能获得增益！",
      "Drinking too many flasks has made the random buffs gained from them stick.": "频繁使用药水延长了随机增益的持续时间。",
      "The shield may be just as important as DPS number charts.": "护盾与输出伤害同样重要。",
      "Moooooooooooreeeeeeeee Healing PLEASE!!!": "请再多给一些治疗量！",
      "Star of speed give me swiftness to strike my foes.": "速度之星，赐予我击打敌人的迅捷！",
      "Drain health from your enemies.": "汲取敌人的生命值。",
      "Attacks so fast you can not even animate fast enough.": "出招快到连动画都跟不上！",
      "In this constellation of dungeon seeking we greet thee with more health.": "在这座星云中为你注入更多生命值。",
      "With faster attack and higher life leech you may someday be invincible.": "极快的攻速与吸血让你有朝一日不可战胜。",
      "Two damage types, maybe someday we will search the stars and find the 3rd one.": "目前有两种伤害类型，也许未来会发现第三种。",
      "Speed through the stars for greater power.": "穿梭于星海，追寻更强的力量。",
      "One day it will be super important to have a lot of this. Wink Wink": "总有一天这项属性会变得极其重要！",
      "Fly, you fools, Fly to the end of that Delve.": "直飞地窖的最深处！",
      "Hunting enemies now grants you boons.": "猎杀敌人可获得强力庇护。",
      "Looking up at the stars has granted additional buff time.": "仰望星空延长了增益的持续时间。",
      "Grant me the true power of the stars. May I destroy the darkness of the cosmos.": "赐予我纯正的星辰之力，驱散宇宙的黑暗。",
      "Wink Wink...": "眨眨眼...",
      "Jump up without being pushed around by bullies.": "轻松跳跃，不再受敌人摆布。",
      "Looking to the stars to decide how to increase those damage numbers.": "参悟星辰以进一步提升伤害数值。",
      "Greater shining light to destroy the dark.": "以璀璨的光芒驱散黑暗。",
      "Oops, did I leave a flask over on this side of the cosmos.": "哎呀，我是不是把药水遗忘在这儿了？",
      "Delving just got a little bit easier.": "地窖探索变得更加轻松。",
      "A little more time to the boon you just got.": "延长刚刚获得的庇护持续时间。",
      "Look up at the sky one night and see the lights above.": "夜幕降临时仰望天空，凝视头顶的光芒。"
    },
    abilitiesMap: {
      "5% chance when critical hitting to increase Critical Hit by 20% for 10 seconds.": "造成暴击时有 5% 概率提升 20% 暴击率，持续 10 秒。",
      "10% chance when critical hitting to increase Critical Hit by 30% for 10 seconds.": "造成暴击时有 10% 概率提升 30% 暴击率，持续 10 秒。",
      "When taking damage, you have a 10% chance to gain a 20% reflect shield for 10 seconds. Has a 1 minute cooldown.": "受到伤害时，有 10% 概率获得 20% 反伤护盾，持续 10 秒。冷却时间 1 分钟。",
      "When taking damage, you have a 20% chance to gain a 30% reflect shield for 10 seconds. Has a 1 minute cooldown.": "受到伤害时，有 20% 概率获得 30% 反伤护盾，持续 10 秒。冷却时间 1 分钟。",
      "When taking damage, you have a 30% chance to gain a 45% reflect shield and 30% damage reduction for 10 seconds. Has a 1 minute cooldown.": "受到伤害时，有 30% 概率获得 45% 反伤护盾与 30% 伤害减免，持续 10 秒。冷却时间 1 分钟。",
      "When dropping below 30% health, gain a 6% Outgoing damage buff and 10% Attack Speed for 10 seconds. 120 second cooldown.": "生命值低于 30% 时，获得 6% 输出伤害加成与 10% 攻击速度，持续 10 秒。冷却时间 120 秒。",
      "When dropping below 40% health, gain a 8% Outgoing damage buff and 10% Attack Speed for 10 seconds. 120 second cooldown.": "生命值低于 40% 时，获得 8% 输出伤害加成与 10% 攻击速度，持续 10 秒。冷却时间 120 秒。",
      "When dropping below 45% health, gain a 10% Outgoing damage buff and 10% Attack Speed for 10 seconds. 120 second cooldown.": "生命值低于 45% 时，获得 10% 输出伤害加成与 10% 攻击速度，持续 10 秒。冷却时间 120 秒。",
      "When dropping below 45% health, gain a 12% Outgoing damage buff and 10% Attack Speed for 15 seconds. 120 second cooldown.": "生命值低于 45% 时，获得 12% 输出伤害加成与 10% 攻击速度，持续 15 秒。冷却时间 15 秒。",
      "Increases amount of ore mined by 10%. ": "采矿开采量提升 10%。",
      "Increases amount of ore mined by 15%. ": "采矿开采量提升 15%。",
      "Increases experience gain by 5%. ": "经验获取量提升 5%。",
      "Increases harvesting by 10%. ": "植物采集量提升 10%。",
      "Increases harvesting by 15%. ": "植物采集量提升 15%。",
      "Slightly increases gathering range when mounted. ": "骑乘状态下微幅提升采集距离。",
      "Moderately increases gathering range when mounted. ": "骑乘状态下中幅提升采集距离。",
      "Greatly increases gathering range when mounted.": "骑乘状态下大幅提升采集距离。",
      "50% chance when using a Flask to gain either a 25% Bonus Damage, 200 Stability, or 200% Bonus Health Regen.": "使用药水时有 50% 概率获得 25% 伤害加成、200 稳定性或 200% 生命回复加成。",
      "100% chance when using a Flask to gain either a 25% Bonus Damage, 200 Stability, or 200% Bonus Health Regen.": "使用药水时 100% 概率获得 25% 伤害加成、200 稳定性或 200% 生命回复加成。",
      "10% chance to gain a random emblem effect when using a flask.": "使用药水时有 10% 概率获得随机徽章效果。",
      "5% chance to gain a flask charge when using a Flask.": "使用药水时有 5% 概率补充 1 瓶药水。",
      "10% chance to gain a flask charge when using a Flask.": "使用药水时有 10% 概率补充 1 瓶药水。",
      "Damaging enemies grants 10% Life Leech.": "攻击敌人时获得 10% 生命偷取。",
      "Damaging enemies grants 20% Life Leech. ": "攻击敌人时获得 20% 生命偷取。",
      "After defeating a Sundered Uplands 5 Star Boss, gain 10% increased Physical and Magic Damage for 4 hours.": "击败断裂之空 5 星 Boss 后，提升 10% 物理与魔法伤害，持续 4 小时。",
      "After defeating a Sundered Uplands 5 Star Boss, gain 15% increased Physical and Magic Damage for 4 hours.": "击败断裂之空 5 星 Boss 后，提升 15% 物理与魔法伤害，持续 4 小时。",
      "After defeating a delve boss, gain 20% damage reduction for 30 minutes. ": "击败地窖 Boss 后，获得 20% 伤害减免，持续 30 分钟。",
      "Increases the Depths boon damage reduction to 25% and duration to 1 hour.": "将地窖庇护的伤害减免提升至 25%，持续时间延长至 1 小时。"
    },
    obtainablesMap: {
      "Grants a Balefire Dragon Egg Fragment when unlocked.": "解锁时获得 1 个灾火龙蛋碎片。",
      "Grants a Caprian Dragon Egg Fragment when upgrading.": "升级时获得 1 个卡普里龙蛋碎片。",
      "Grants a Caprian Dragon Egg Fragment when upgrading": "升级时获得 1 个卡普里龙蛋碎片",
      "Grants Ursa Minor when upgrading": "升级时获得小熊座宠物",
      "Grants Ursa Major when upgrading": "升级时获得大熊座宠物",
      "Grants Staruable when upgrading": "升级时获得 Staruable",
      "Grants Star Dust when upgrading": "升级时获得星尘",
      "Grants Star Sebastian when upgrading": "升级时获得 Star Sebastian",
      "Grants Charter's Chair when upgrading": "升级时获得宪章之椅",
      "Grants Starry Skyfire when upgrading": "升级时获得星空天火",
      "Grants Scorpius when upgrading": "升级时获得蝎子"
    }
  }
};