export const venturineCalcContent = {
  en: {
    tabV2S: "Venturine to Signets",
    tabS2V: "Signets to Venturine",
    tabContinue: "Continue Crafting",
    tabFromCost: "From Cost",
    labelVenturine: "Amount of Venturine:",
    labelDesiredSignets: "Desired Signets:",
    labelCurrentCrafted: "Current Crafted:",
    labelDesiredAdditional: "Desired Additional:",
    labelCurrentCost: "Current Cost (Venturine):",
    calculate: "Calculate",
    placeholderResult: "Enter values and hit Calculate to see results.",
    materialsNeeded: "Materials Needed",
    errVenturine: "Enter a valid amount of Venturine.",
    errSignets: "Enter a valid number of Signets.",
    errValid: "Please enter valid values.",
    msgV2S: (i, v) => `You can craft <strong>${i}</strong> Signets with <strong>${v}</strong> Venturine.`,
    msgS2V: (total, s) => `You need <strong>${total}</strong> Venturine to craft <strong>${s}</strong> Signets.`,
    msgContinue: (total, desired) => `You'll need <strong>${total}</strong> Venturine to craft <strong>${desired}</strong> more Signets.`,
    msgFromCost: (desired, needed) => `To craft <strong>${desired}</strong> Signets you'll need: <strong>≈${needed}</strong> Venturine`
  },
  fr: {
    tabV2S: "Venturine en Sceaux",
    tabS2V: "Sceaux en Venturine",
    tabContinue: "Continuer le Craft",
    tabFromCost: "Depuis le Coût",
    labelVenturine: "Quantité de Venturine :",
    labelDesiredSignets: "Sceaux souhaités :",
    labelCurrentCrafted: "Sceaux déjà craftés :",
    labelDesiredAdditional: "Sceaux supplémentaires :",
    labelCurrentCost: "Coût actuel (Venturine) :",
    calculate: "Calculer",
    placeholderResult: "Saisissez les valeurs et appuyez sur Calculer.",
    materialsNeeded: "Matériaux nécessaires",
    errVenturine: "Saisissez un montant valide de Venturine.",
    errSignets: "Saisissez un nombre valide de Sceaux.",
    errValid: "Veuillez saisir des valeurs valides.",
    msgV2S: (i, v) => `Vous pouvez fabriquer <strong>${i}</strong> Sceaux avec <strong>${v}</strong> Venturine.`,
    msgS2V: (total, s) => `Il vous faut <strong>${total}</strong> Venturine pour fabriquer <strong>${s}</strong> Sceaux.`,
    msgContinue: (total, desired) => `Il vous faudra <strong>${total}</strong> Venturine pour fabriquer <strong>${desired}</strong> Sceaux de plus.`,
    msgFromCost: (desired, needed) => `Pour fabriquer <strong>${desired}</strong> Sceaux vous aurez besoin de : <strong>≈${needed}</strong> Venturine`
  },
  es: {
    tabV2S: "Venturina a Sellos",
    tabS2V: "Sellos a Venturina",
    tabContinue: "Continuar Creación",
    tabFromCost: "Desde el Costo",
    labelVenturine: "Cantidad de Venturina:",
    labelDesiredSignets: "Sellos deseados:",
    labelCurrentCrafted: "Actualmente creados:",
    labelDesiredAdditional: "Adicionales deseados:",
    labelCurrentCost: "Costo Actual (Venturina):",
    calculate: "Calcular",
    placeholderResult: "Introduce valores y presiona Calcular para ver resultados.",
    materialsNeeded: "Materiales Necesarios",
    errVenturine: "Introduce una cantidad válida de Venturina.",
    errSignets: "Introduce un número válido de Sellos.",
    errValid: "Por favor, introduce valores válidos.",
    msgV2S: (i, v) => `Puedes crear <strong>${i}</strong> Sellos con <strong>${v}</strong> Venturina.`,
    msgS2V: (total, s) => `Necesitas <strong>${total}</strong> Venturina para crear <strong>${s}</strong> Sellos.`,
    msgContinue: (total, desired) => `Necesitarás <strong>${total}</strong> Venturina para crear <strong>${desired}</strong> Sellos más.`,
    msgFromCost: (desired, needed) => `Para crear <strong>${desired}</strong> Sellos necesitarás: <strong>≈${needed}</strong> Venturina`
  },
  zh: {
    tabV2S: "冒险石 → 印章",
    tabS2V: "印章 → 冒险石",
    tabContinue: "继续锻造计算",
    tabFromCost: "按当前消耗计算",
    labelVenturine: "冒险石总数：",
    labelDesiredSignets: "目标印章数量：",
    labelCurrentCrafted: "当前已制作次数：",
    labelDesiredAdditional: "额外目标制作数：",
    labelCurrentCost: "当前单次消耗 (冒险石)：",
    calculate: "开始计算",
    placeholderResult: "输入数值并点击开始计算查看结果。",
    materialsNeeded: "所需材料数量",
    errVenturine: "请输入有效的冒险石数量。",
    errSignets: "请输入有效的印章数量。",
    errValid: "请输入有效的数值。",
    msgV2S: (i, v) => `使用 <strong>${v}</strong> 冒险石，你最多可以锻造 <strong>${i}</strong> 个印章。`,
    msgS2V: (total, s) => `锻造 <strong>${s}</strong> 个印章，你总共需要 <strong>${total}</strong> 冒险石。`,
    msgContinue: (total, desired) => `再额外锻造 <strong>${desired}</strong> 个印章，你还需要 <strong>${total}</strong> 冒险石。`,
    msgFromCost: (desired, needed) => `锻造 <strong>${desired}</strong> 个印章，你大约需要：<strong>≈${needed}</strong> 冒险石`
  }
};